/obj/machinery/vending/autodrobe
	name = "AutoDrobe"
	desc = "Автомат по продаже костюмов на любой вкус и цвет."
	icon_state = "theater_off"
	panel_overlay = "theater_panel"
	screen_overlay = "theater"
	lightmask_overlay = "theater_lightmask"
	broken_overlay = "theater_broken"
	broken_lightmask_overlay = "theater_broken_lightmask"
	deny_overlay = "theater_deny"
	slogan_list = list(
		"Приод+енься для усп+еха!",
		"Од+етый и об+утый!",
		"Пришл+о вр+емя ш+оу!",
		"Зач+ем оставл+ять стиль на произв+ол судьб+ы? Исп+ользуй AutoDrobe!",
	)
	vend_delay = 15
	vend_reply = "Спас+ибо за исп+ользование AutoDrobe!"

	product_categories = list(

		list(
			"name" = "Головные уборы",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/colour/headband = 10,
				/obj/item/clothing/head/chicken = 10,
				/obj/item/clothing/head/helmet/gladiator = 10,
				/obj/item/clothing/head/flatcap = 10,
				/obj/item/clothing/head/griffin = 10,
				/obj/item/clothing/head/that = 10,
				/obj/item/clothing/head/bowlerhat = 10,
				/obj/item/clothing/head/plaguedoctorhat = 10,
				/obj/item/clothing/head/pirate = 10,
				/obj/item/clothing/head/bandana = 10,
				/obj/item/clothing/head/bandana = 10,
				/obj/item/clothing/head/colour/headband = 10,
				/obj/item/clothing/head/ushanka = 10,
				/obj/item/clothing/head/wizard/marisa/fake = 10,
				/obj/item/clothing/head/witchwig = 10,
				/obj/item/clothing/head/wizard/fake = 10,
				/obj/item/clothing/head/rabbitears = 10,
				/obj/item/clothing/head/sombrero = 10,
				/obj/item/clothing/head/jester = 10,
				/obj/item/clothing/head/rockso = 10,
				/obj/item/clothing/head/snowman = 10,
				/obj/item/clothing/head/cueball = 10,
				/obj/item/clothing/head/zepelli = 10,
				/obj/item/clothing/head/shapka_pepega = 10,
			),
		),
		list(
			"name" = "Аксессуары",
			"icon" = "glasses",
			"products" = list(
				/obj/item/clothing/glasses/gglasses = 10,
				/obj/item/clothing/glasses/monocle = 10,
				/obj/item/clothing/accessory/waistcoat = 10,
				/obj/item/clothing/accessory/blue = 10,
				/obj/item/clothing/accessory/red = 10,
				/obj/item/clothing/accessory/black = 10,
				/obj/item/clothing/accessory/horrible = 10,
				/obj/item/clothing/accessory/armguard = 10,
				/obj/item/clothing/neck/poncho = 10,
				/obj/item/clothing/neck/cloak/toggle/owlwings = 10,
				/obj/item/clothing/neck/cloak/toggle/owlwings/griffinwings = 10,
			),
		),
		list(
			"name" = "Маски",
			"icon" = "mask-face",
			"products" = list(
				/obj/item/clothing/mask/gas/owl_mask = 10,
				/obj/item/clothing/mask/face/bat = 10,
				/obj/item/clothing/mask/face/bee = 10,
				/obj/item/clothing/mask/face/bear = 10,
				/obj/item/clothing/mask/face/raven = 10,
				/obj/item/clothing/mask/face/jackal = 10,
				/obj/item/clothing/mask/face/fox = 10,
				/obj/item/clothing/mask/face/tribal = 10,
				/obj/item/clothing/mask/face/rat = 10,
				/obj/item/clothing/mask/fakemoustache = 10,
				/obj/item/clothing/mask/gas/plaguedoctor = 10,
				/obj/item/clothing/mask/gas/cyborg = 10,
				/obj/item/clothing/mask/gas/clown_hat = 10,
				/obj/item/clothing/mask/gas/mime/sexy = 10,
				/obj/item/clothing/mask/gas/mime/old = 10,
				/obj/item/clothing/mask/bandana = 10,
				/obj/item/clothing/mask/bandana/black = 10,
				/obj/item/clothing/mask/gas/ghostface = 10,
			),
		),
		list(
			"name" = "Униформа",
			"icon" = "shirt",
			"products" = list(
				/obj/item/clothing/under/gladiator = 10,
				/obj/item/clothing/under/gimmick/rank/captain/suit = 10,
				/obj/item/clothing/under/schoolgirl = 10,
				/obj/item/clothing/under/blackskirt = 10,
				/obj/item/clothing/under/owl = 10,
				/obj/item/clothing/under/griffin = 10,
				/obj/item/clothing/under/suit_jacket = 10,
				/obj/item/clothing/under/kilt = 10,
				/obj/item/clothing/under/sl_suit = 10,
				/obj/item/clothing/under/waiter = 10,
				/obj/item/clothing/under/pirate = 10,
				/obj/item/clothing/under/pirate_rags = 10,
				/obj/item/clothing/under/soviet = 10,
				/obj/item/clothing/under/sundress = 10,
				/obj/item/clothing/under/rank/clown/sexy = 10,
				/obj/item/clothing/under/rank/clown/clussy = 10,
				/obj/item/clothing/under/sexymime = 10,
				/obj/item/clothing/under/maid = 10,
				/obj/item/clothing/under/janimaid = 10,
				/obj/item/clothing/under/jester = 10,
				/obj/item/clothing/under/pennywise = 10,
				/obj/item/clothing/under/rockso = 10,
				/obj/item/clothing/under/sweettooth = 10,
				/obj/item/clothing/under/pants/camo = 10,
				/obj/item/clothing/under/singerb = 10,
				/obj/item/clothing/under/singery = 10,
				/obj/item/clothing/under/red_chaps = 10,
				/obj/item/clothing/under/white_chaps = 10,
				/obj/item/clothing/under/tan_chaps = 10,
				/obj/item/clothing/under/brown_chaps = 10,
				/obj/item/clothing/under/scratch = 10,
				/obj/item/clothing/under/victdress = 10,
				/obj/item/clothing/under/victdress/red = 10,
				/obj/item/clothing/under/victsuit = 10,
				/obj/item/clothing/under/victsuit/redblk = 10,
				/obj/item/clothing/under/victsuit/red = 10,
				/obj/item/clothing/under/redhawaiianshirt = 10,
				/obj/item/clothing/under/pinkhawaiianshirt = 10,
				/obj/item/clothing/under/bluehawaiianshirt = 10,
				/obj/item/clothing/under/orangehawaiianshirt = 10,
				/obj/item/clothing/under/ussptracksuit_red = 10,
				/obj/item/clothing/under/ussptracksuit_blue = 10,
				/obj/item/clothing/under/dress50s = 10,
				/obj/item/clothing/under/tourist_suit = 10,
			),
		),
		list(
			"name" = "Верхняя одежда",
			"icon" = "vest",
			"products" = list(
				/obj/item/clothing/suit/chickensuit = 10,
				/obj/item/clothing/suit/storage/labcoat/mad = 10,
				/obj/item/clothing/suit/bio_suit/plaguedoctorsuit = 10,
				/obj/item/clothing/suit/apron = 10,
				/obj/item/clothing/suit/jacket/miljacket = 10,
				/obj/item/clothing/suit/jacket/miljacket/white = 10,
				/obj/item/clothing/suit/jacket/miljacket/desert = 10,
				/obj/item/clothing/suit/jacket/miljacket/navy = 10,
				/obj/item/clothing/suit/pirate_brown = 10,
				/obj/item/clothing/suit/pirate_black = 10,
				/obj/item/clothing/suit/apron/overalls = 10,
				/obj/item/clothing/suit/wizrobe/fake = 10,
				/obj/item/clothing/suit/imperium_monk = 10,
				/obj/item/clothing/suit/holidaypriest = 10,
				/obj/item/clothing/suit/wizrobe/marisa/fake = 10,
				/obj/item/clothing/suit/hooded/carp_costume = 10,
				/obj/item/clothing/suit/hooded/penguin_costume = 10,
				/obj/item/clothing/suit/hooded/bee_costume = 10,
				/obj/item/clothing/suit/snowman = 10,
				/obj/item/clothing/suit/victcoat = 10,
				/obj/item/clothing/suit/victcoat/red = 10,
				/obj/item/clothing/suit/tailcoat = 10,
				/obj/item/clothing/suit/draculacoat = 10,
				/obj/item/clothing/suit/hooded/ghostfacesuit = 10,
				/obj/item/clothing/suit/hooded/ghostfacesuit/devil = 10,
			),
		),
		list(
			"name" = "Обувь",
			"icon" = "socks",
			"products" = list(
				/obj/item/clothing/shoes/jackboots = 10,
				/obj/item/clothing/shoes/jackboots/high = 10,
				/obj/item/clothing/shoes/griffin = 10,
				/obj/item/clothing/shoes/singery = 10,
				/obj/item/clothing/shoes/singerb = 10,
			),
		),
		list(
			"name" = "Прочее",
			"icon" = "ellipsis",
			"products" = list(
				/obj/item/cane = 10,
				/obj/item/twohanded/staff/broom = 10,
				/obj/item/twohanded/staff = 10,
			),
		),
	)

	contraband = list(
		/obj/item/clothing/suit/judgerobe = 1,
		/obj/item/clothing/head/powdered_wig = 1,
		/obj/item/gun/magic/wand = 1,
		/obj/item/clothing/mask/balaclava =1,
		/obj/item/clothing/under/syndicate/blackops_civ = 1,
		/obj/item/clothing/glasses/thermal_fake = 1,
		/obj/item/clothing/mask/horsehead = 2,
	)

	premium = list(
		/obj/item/clothing/suit/hgpirate = 1,
		/obj/item/clothing/head/hgpiratecap = 1,
		/obj/item/clothing/head/helmet/roman/fake = 1,
		/obj/item/clothing/head/helmet/roman/legionaire/fake = 1,
		/obj/item/clothing/under/roman = 1,
		/obj/item/clothing/shoes/roman = 1,
		/obj/item/shield/riot/roman/fake = 1,
		/obj/item/clothing/under/cuban_suit = 1,
		/obj/item/clothing/head/cuban_hat = 1,
		/obj/item/clothing/under/ussptracksuit_black = 1,
		/obj/item/clothing/under/ussptracksuit_white = 1,
		/obj/item/clothing/under/steampunkdress = 1,
		/obj/item/clothing/suit/hooded/hijab = 1,
	)

	refill_canister = /obj/item/vending_refill/autodrobe

/obj/machinery/vending/autodrobe/get_ru_names()
	return list(
		NOMINATIVE = "торговый автомат AutoDrobe",
		GENITIVE = "торгового автомата AutoDrobe",
		DATIVE = "торговому автомату AutoDrobe",
		ACCUSATIVE = "торговый автомат AutoDrobe",
		INSTRUMENTAL = "торговым автоматом AutoDrobe",
		PREPOSITIONAL = "торговом автомате AutoDrobe",
	)
