GLOBAL_LIST_INIT(phobia_types, list(
	"aliens" = "инопланетян",
	"anime" = "аниме",
	"authority" = "начальства",
	"birds" = "птиц",
	"blood" = "крови",
	"clowns" = "клоунов",
	"conspiracies" = "заговоров",
	"doctors" = "врачей",
	"falling" = "высоты",
	"fish" = "рыб",
	"greytide" = "ассистентов",
	"guns" = "оружия",
	"insects" = "насекомых",
	"lizards" = "ящеров",
	"ocky icky" = "всего мерзкого",
	"robots" = "роботов",
	"security" = "службы безопасности",
	"skeletons" = "скелетов",
	"snakes" = "змей",
	"space" = "космоса",
	"spiders" = "пауков",
	"strangers" = "незнакомцев",
	"the supernatural" = "сверхъестественного",
))

GLOBAL_LIST_INIT(phobia_random_types, list(
	"aliens",
	"anime",
	"authority",
	"birds",
	"blood",
	"clowns",
	"doctors",
	"falling",
	"fish",
	"greytide",
	"guns",
	"insects",
	"lizards",
	"robots",
	"security",
	"skeletons",
	"snakes",
	"space",
	"spiders",
	"strangers",
	"the supernatural",
))

GLOBAL_LIST_INIT(phobia_regexes, list(
	"aliens" = construct_phobia_regex("aliens"),
	"anime" = construct_phobia_regex("anime"),
	"authority" = construct_phobia_regex("authority"),
	"birds" = construct_phobia_regex("birds"),
	"blood" = construct_phobia_regex("blood"),
	"clowns" = construct_phobia_regex("clowns"),
	"conspiracies" = construct_phobia_regex("conspiracies"),
	"doctors" = construct_phobia_regex("doctors"),
	"falling" = construct_phobia_regex("falling"),
	"fish" = construct_phobia_regex("fish"),
	"greytide" = construct_phobia_regex("greytide"),
	"guns" = construct_phobia_regex("guns"),
	"insects" = construct_phobia_regex("insects"),
	"lizards" = construct_phobia_regex("lizards"),
	"ocky icky" = construct_phobia_regex("ocky icky"),
	"robots" = construct_phobia_regex("robots"),
	"security" = construct_phobia_regex("security"),
	"skeletons" = construct_phobia_regex("skeletons"),
	"snakes" = construct_phobia_regex("snakes"),
	"space" = construct_phobia_regex("space"),
	"spiders" = construct_phobia_regex("spiders"),
	"strangers" = construct_phobia_regex("strangers"),
	"the supernatural" = construct_phobia_regex("the supernatural"),
))

GLOBAL_LIST_INIT(phobia_mobs, list(
	"aliens" = typecacheof(list(
		/mob/living/carbon/alien,
		/mob/living/simple_animal/hostile/alien,
		/mob/living/simple_animal/slime,
	)),
	"anime" = typecacheof(list(/mob/living/simple_animal/hostile/guardian)),
	"authority" = typecacheof(list(
		/mob/living/silicon/ai,
		/mob/living/simple_animal/bot/secbot,
	)),
	"birds" = typecacheof(list(
		/mob/living/simple_animal/chicken,
		/mob/living/simple_animal/goose,
		/mob/living/simple_animal/parrot,
		/mob/living/simple_animal/pet/penguin,
	)),
	"conspiracies" = typecacheof(list(
		/mob/living/silicon/ai,
		/mob/living/simple_animal/bot/secbot,
	)),
	"doctors" = typecacheof(list(/mob/living/simple_animal/bot/medbot)),
	"fish" = typecacheof(list(/mob/living/simple_animal/hostile/carp)),
	"insects" = typecacheof(list(
		/mob/living/basic/cockroach,
		/mob/living/simple_animal/hostile/poison/bees,
	)),
	"lizards" = typecacheof(list(
		/mob/living/simple_animal/hostile/lizard,
		/mob/living/simple_animal/lizard,
	)),
	"robots" = typecacheof(list(
		/mob/living/silicon,
		/mob/living/simple_animal/bot,
	)),
	"security" = typecacheof(list(/mob/living/simple_animal/bot/secbot)),
	"skeletons" = typecacheof(list(/mob/living/simple_animal/hostile/skeleton)),
	"snakes" = typecacheof(list(/mob/living/simple_animal/hostile/retaliate/poison/snake)),
	"spiders" = typecacheof(list(
		/mob/living/simple_animal/hostile/poison/giant_spider,
		/mob/living/simple_animal/hostile/poison/terror_spider,
	)),
	"the supernatural" = typecacheof(list(
		/mob/dead/observer,
		/mob/living/simple_animal/demon,
		/mob/living/simple_animal/hostile/construct,
		/mob/living/simple_animal/hostile/faithless,
		/mob/living/simple_animal/hostile/scarybat,
		/mob/living/simple_animal/hostile/skeleton,
		/mob/living/simple_animal/hostile/zombie,
		/mob/living/simple_animal/revenant,
		/mob/living/simple_animal/shade,
	)),
))

GLOBAL_LIST_INIT(phobia_objs, list(
	"aliens" = typecacheof(list(
		/obj/item/abductor,
		/obj/machinery/abductor,
		/obj/structure/alien,
	)),
	"anime" = typecacheof(list(
		/obj/item/clothing/head/collectable/kitty,
		/obj/item/clothing/head/helmet/space/space_ninja,
		/obj/item/clothing/head/kitty,
		/obj/item/clothing/mask/gas/space_ninja,
		/obj/item/clothing/suit/space/space_ninja,
		/obj/item/cursed_katana,
		/obj/item/melee/energy_katana,
		/obj/item/melee/katana,
		/obj/item/throwing_star,
		/obj/item/toy/katana,
	)),
	"authority" = typecacheof(list(
		/obj/item/card/id/gold,
		/obj/item/card/id/silver,
		/obj/item/clothing/neck/cloak/captain,
		/obj/item/clothing/neck/cloak/chief_engineer,
		/obj/item/clothing/neck/cloak/chief_medical_officer,
		/obj/item/clothing/neck/cloak/head_of_personnel,
		/obj/item/clothing/neck/cloak/head_of_security,
		/obj/item/clothing/neck/cloak/quartermaster,
		/obj/item/clothing/neck/cloak/research_director,
		/obj/item/clothing/under/rank/cargo,
		/obj/item/clothing/under/rank/captain,
		/obj/item/clothing/under/rank/chief_engineer,
		/obj/item/clothing/under/rank/chief_medical_officer,
		/obj/item/clothing/under/rank/head_of_personnel,
		/obj/item/clothing/under/rank/head_of_security,
		/obj/item/clothing/under/rank/research_director,
		/obj/item/radio/headset/heads,
		/obj/item/stamp/captain,
		/obj/item/stamp/ce,
		/obj/item/stamp/cmo,
		/obj/item/stamp/hop,
		/obj/item/stamp/hos,
		/obj/item/stamp/qm,
		/obj/item/stamp/rd,
		/obj/item/toy/figure/captain,
		/obj/item/toy/figure/ce,
		/obj/item/toy/figure/cmo,
		/obj/item/toy/figure/hop,
		/obj/item/toy/figure/hos,
		/obj/item/toy/figure/rd,
		/obj/machinery/door/airlock/command,
	)),
	"birds" = typecacheof(list(
		/obj/item/clothing/head/chicken,
		/obj/item/clothing/head/griffin,
		/obj/item/clothing/head/plaguedoctorhat,
		/obj/item/clothing/mask/gas/owl_mask,
		/obj/item/clothing/suit/chickensuit,
		/obj/item/reagent_containers/food/snacks/egg,
	)),
	"blood" = typecacheof(list(
		/obj/effect/decal/cleanable/blood,
		/obj/item/organ/external,
		/obj/item/organ/internal,
	)),
	"clowns" = typecacheof(list(
		/obj/item/bikehorn,
		/obj/item/clothing/mask/gas/clown_hat,
		/obj/item/clothing/shoes/clown_shoes,
		/obj/item/reagent_containers/food/snacks/grown/banana,
	)),
	"conspiracies" = typecacheof(list(
		/obj/item/abductor,
		/obj/item/card/id/centcom,
		/obj/item/radio/headset/heads,
		/obj/item/stamp/centcom,
		/obj/item/toy/figure/dsquad,
		/obj/machinery/abductor,
		/obj/machinery/door/airlock/centcom,
	)),
	"doctors" = typecacheof(list(
		/obj/item/reagent_containers/syringe,
		/obj/item/scalpel,
		/obj/item/stack/medical,
		/obj/item/storage/firstaid,
		/obj/machinery/dna_scannernew,
	)),
	"fish" = typecacheof(list(
		/obj/item/fish,
		/obj/item/reagent_containers/food/snacks/carpmeat,
	)),
	"greytide" = typecacheof(list(
		/obj/item/clothing/under/color/grey,
		/obj/item/storage/toolbox,
	)),
	"guns" = typecacheof(list(
		/obj/item/ammo_box,
		/obj/item/ammo_casing,
		/obj/item/grenade,
		/obj/item/gun,
	)),
	"insects" = typecacheof(list(
		/obj/item/bee_briefcase,
		/obj/item/clothing/mask/face/bee,
		/obj/item/clothing/suit/hooded/bee_costume,
		/obj/structure/beebox,
	)),
	"lizards" = typecacheof(list(
		/obj/item/clothing/shoes/cowboy/lizard,
		/obj/item/holder/lizard,
		/obj/item/reagent_containers/food/snacks/monstermeat/lizardmeat,
		/obj/item/stack/sheet/animalhide/lizard,
		/obj/item/toy/plushie/lizard_plushie,
	)),
	"ocky icky" = typecacheof(list(
		/obj/effect/decal/cleanable/blood,
		/obj/effect/decal/cleanable/vomit,
	)),
	"robots" = typecacheof(list(/obj/machinery/computer/aifixer)),
	"security" = typecacheof(list(
		/obj/item/clothing/glasses/hud/security,
		/obj/item/clothing/under/rank/security,
		/obj/item/melee/baton,
		/obj/item/restraints/handcuffs,
		/obj/item/storage/belt/security,
	)),
	"skeletons" = typecacheof(list(
		/obj/effect/decal/remains,
		/obj/item/stack/sheet/bone,
		/obj/structure/closet/body_bag,
	)),
	"snakes" = typecacheof(list(
		/obj/item/holder/snake,
		/obj/item/rod_of_asclepius,
		/obj/item/toy/plushie/snakeplushie,
	)),
	"spiders" = typecacheof(list(/obj/structure/spider)),
	"the supernatural" = typecacheof(list(
		/obj/effect/gateway,
		/obj/effect/rune,
		/obj/item/soulstone,
		/obj/item/tome,
		/obj/structure/cult,
	)),
))

GLOBAL_LIST_INIT(phobia_turfs, list(
	"aliens" = typecacheof(list(
		/turf/simulated/floor/indestructible/abductor,
		/turf/simulated/floor/mineral/abductor,
		/turf/simulated/wall/mineral/alien,
	)),
	"falling" = typecacheof(list(
		/turf/simulated/floor/chasm,
		/turf/simulated/openspace,
	)),
	"space" = typecacheof(list(/turf/space)),
	"the supernatural" = typecacheof(list(
		/turf/simulated/floor/engine/cult,
		/turf/simulated/wall/cult,
	)),
))

GLOBAL_LIST_INIT(phobia_species, list(
	"aliens" = typecacheof(list(
		/datum/species/abductor,
		/datum/species/diona,
		/datum/species/grey,
		/datum/species/shadow,
		/datum/species/slime,
	)),
	"anime" = typecacheof(list(/datum/species/tajaran)),
	"birds" = typecacheof(list(/datum/species/vox)),
	"conspiracies" = typecacheof(list(
		/datum/species/abductor,
		/datum/species/unathi,
	)),
	"insects" = typecacheof(list(
		/datum/species/kidan,
		/datum/species/moth,
		/datum/species/wryn,
	)),
	"lizards" = typecacheof(list(/datum/species/unathi)),
	"robots" = typecacheof(list(/datum/species/machine)),
	"skeletons" = typecacheof(list(
		/datum/species/plasmaman,
		/datum/species/skeleton,
	)),
	"the supernatural" = typecacheof(list(/datum/species/shadow)),
))

/proc/construct_phobia_regex(phobia_type)
	var/list/words = strings(PHOBIA_FILE, phobia_type)
	if(!length(words))
		CRASH("phobia [phobia_type] has no entries")

	var/list/quoted = list()
	for(var/word in words)
		quoted += REGEX_QUOTE(word)
	return regex("(^|\[^а-яёА-ЯЁa-zA-Z\])([jointext(quoted, "|")])(\[а-яёА-ЯЁa-zA-Z\]*)", "i")
