/datum/syndie_bundle
	var/bundle_name
	var/static/list/bundle_items = list()
		"Spy" = list( spy
						"Name" = "\improper 'Spy' Bundle",
						"Desc" = "Complete your objectives quietly with this compilation of stealthy items.",
						/obj/item/storage/box/syndie_kit/chameleon,
						/obj/item/door_remote/omni/access_tuner,
						/obj/item/implanter/storage,
						/obj/item/pen/edagger,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/shoes/chameleon/noslip,
						/obj/item/camera_bug,
						/obj/item/multitool/ai_detect,
						/obj/item/encryptionkey/syndicate,
						/obj/item/twohanded/garrote,
						/obj/item/pinpointer/advpinpointer,
						/obj/item/storage/fancy/cigarettes/cigpack_syndicate,
						/obj/item/flashlight/emp,
						/obj/item/clothing/glasses/hud/security/chameleon,
						/obj/item/chameleon),
		"Thief" = list(thief
						"Name" = "\improper 'Thief' bundle",
						"Desc" = "Steal from friends, enemies, and interstellar megacorporations alike!",
						/obj/item/storage/box/syndie_kit/counterfeiter_bundle,
						/obj/item/gun/energy/kinetic_accelerator/crossbow,
						/obj/item/chameleon,
						/obj/item/clothing/glasses/chameleon/thermal,
						/obj/item/clothing/gloves/color/black/thief,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/shoes/chameleon/noslip,
						/obj/item/storage/backpack/satchel_flat,
						/obj/item/encryptionkey/syndicate),
		"Agent 007" = list(bond
						"Name" = "\improper 'Agent 007' bundle",
						"Desc" = "Find and eliminate your targets quietly and effectively with this kit.",
						/obj/item/clothing/glasses/hud/security/chameleon,
						/obj/item/grenade/syndieminibomb // Скин ручки бы.
						/obj/item/gun/projectile/automatic/pistol,
						/obj/item/suppressor,
						/obj/item/ammo_box/magazine/m10mm,
						/obj/item/ammo_box/magazine/m10mm/hp,
						/obj/item/ammo_box/magazine/m10mm/ap,
						/obj/item/ammo_box/magazine/m10mm/ap,
						/obj/item/clothing/under/suit_jacket/really_black,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/suit/storage/lawyer/blackjacket/armored,
						/obj/item/encryptionkey/syndicate,
						/obj/item/reagent_containers/food/drinks/drinkingglass/alliescocktail,
						/obj/item/storage/box/syndie_kit/emp,
						/obj/item/CQC_manual),
		"Sabotager" = list(sabotager
						"Name" = "\improper 'Sabotage' bundle",
						"Desc" = "Wreak havoc and destruction on the station with this kit.",
						/obj/item/grenade/plastic/c4,
						/obj/item/grenade/plastic/c4,
						/obj/item/camera_bug,
						/obj/item/powersink,
						/obj/item/cartridge/syndicate,
						/obj/item/rcd/preloaded,
						/obj/item/card/emag,
						/obj/item/clothing/gloves/color/yellow,
						/obj/item/grenade/syndieminibomb,
						/obj/item/grenade/clusterbuster/n2o,
						/obj/item/storage/box/syndie_kit/space,
						/obj/item/encryptionkey/syndicate),
		"Bank Robber" = list(payday
						"Name" = "\improper 'Heist' bundle",
						"Desc" = "Alright guys, today we're performing a heist on a space station owned by a greedy corporation.",
						/obj/item/implanter/freedom, // Сделать однозарядный.
						/obj/item/gun/projectile/revolver,
						/obj/item/ammo_box/speedloader/a357,
						/obj/item/ammo_box/speedloader/a357,
						/obj/item/card/emag,
						/obj/item/jammer,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/under/suit_jacket/really_black,
						/obj/item/clothing/suit/storage/lawyer/blackjacket/armored,
						/obj/item/clothing/gloves/color/latex/nitrile,
						/obj/item/clothing/mask/gas/clown_hat,
						/obj/item/thermal_drill/diamond_drill, // Сделать порт с оффов.
						/obj/item/encryptionkey/syndicate),
		"Implanter" = list(implant
						"Name" = "\improper 'Bio-chip' bundle",
						"Desc" = "A few useful bio-chips to give you some options for when you inevitably get captured by the Security.",
						/obj/item/implanter/stealth,
						/obj/item/implanter/freedom,
						/obj/item/implanter/emp,
						/obj/item/implanter/adrenalin,
						/obj/item/implanter/explosive,
						/obj/item/implanter/storage,
						/obj/item/encryptionkey/syndicate),
		"Hacker" = list(hacker
						"Name" = "\improper 'Hacker' bundle",
						"Desc" = "A kit with everything you need to hack into and disrupt the Station, AI, its cyborgs and the Security team.",
						/obj/item/melee/energy/sword/saber,
						/obj/item/card/id/syndicate,
						/obj/item/storage/box/syndie_kit/emp,
						/obj/item/camera_bug,
						/obj/item/door_remote/omni/access_tuner,
						/obj/item/implanter/freedom, // Сделать однозарядный.
						/obj/item/aiModule/syndicate,
						/obj/item/card/emag,
						/obj/item/encryptionkey/syndicate,
						/obj/item/encryptionkey/binary,
						/obj/item/aiModule/toyAI,
						/obj/item/storage/belt/military/traitor/hacker,
						/obj/item/clothing/gloves/combat,
						/obj/item/flashlight/emp),
		"Dark Lord" = list(darklord
						"Name" = "\improper 'Darklord' bundle",
						"Desc" = "Turn your anger into hate and your hate into suffering with a mix of energy swords and magical powers. DO IT.",
/*						/obj/item/t_scanner
						/obj/item/clothing/gloves/color/yellow/power */	// Для Потрошельного.
						/obj/item/melee/energy/sword/saber/red,
						/obj/item/melee/energy/sword/saber/red,
						/obj/item/dnainjector/telemut/darkbundle,
						/obj/item/clothing/suit/hooded/chaplain_hoodie,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/shoes/chameleon/noslip,
						/obj/item/clothing/mask/chameleon,
						/obj/item/encryptionkey/syndicate),
		"Sniper" = list(professional
						"Name" = "\improper 'Sniper' Bundle",
						"Desc" = "Suit up and handle yourself like a professional with a long-distance sniper rifle, additional .50 standard and penetrator rounds and thermal glasses to easily scope out your target.",
						/obj/item/gun/projectile/automatic/sniper_rifle/syndicate/penetrator,
						/obj/item/projectile/bullet/sniper/compact,
						/obj/item/ammo_box/magazine/sniper_rounds/compact/penetrator,
						/obj/item/ammo_box/magazine/sniper_rounds/compact/penetrator,
						/obj/item/ammo_box/magazine/sniper_rounds/compact/soporific,
						/obj/item/clothing/glasses/chameleon/thermal,
						/obj/item/clothing/gloves/combat,
						/obj/item/clothing/under/suit_jacket/really_black,
						/obj/item/clothing/suit/storage/lawyer/blackjacket/armored,
						/obj/item/pen/edagger,
						/obj/item/encryptionkey/syndicate),
		"Officer" = list(officer
						"Name" = "\improper 'Officer' bundle",
						"Desc" = "Disguise yourself in plain sight as a Security officer.",
						/obj/item/security_voucher,
						/obj/item/encryptionkey/syndicate,
						/obj/item/card/id/syndicate,
						/obj/item/clothing/glasses/hud/security/chameleon,
						/obj/item/clothing/mask/chameleon,
						/obj/item/clothing/accessory/holster,
						/obj/item/storage/belt/military/traitor/sec,
						/obj/item/pinpointer/advpinpointer,
						/obj/item/gun/projectile/automatic/pistol,
						/obj/item/ammo_box/magazine/m10mm,
						/obj/item/ammo_box/magazine/m10mm/ap,
						/obj/item/ammo_box/magazine/m10mm/fire,
						/obj/item/ammo_box/magazine/m10mm/hp,
						/obj/item/storage/box/sec,
						/obj/item/restraints/handcuffs,
						/obj/item/flash,
						/obj/item/implanter/mindshield,
						/obj/item/clothing/suit/armor/vest/security),
		"Operative" = list(metaops
						"Name" = "\improper 'Metaops' bundle",
						"Desc" = "Wreak chaos and disguise yourself as a nuclear operative.",
						/obj/item/clothing/suit/space/hardsuit/syndi/elite,
						/obj/item/gun/projectile/automatic/shotgun/bulldog/standart,
						/obj/item/implanter/explosive,
						/obj/item/ammo_box/magazine/m12g/standart,
						/obj/item/ammo_box/magazine/m12g/standart,
						/obj/item/grenade/plastic/c4,
						/obj/item/grenade/plastic/c4,d
						/obj/item/card/emag,
						/obj/item/encryptionkey/syndicate)
		"Infiltrator" = list(infiltrator
						"Name" = "\improper 'Infiltrator' bundle",
						"Desc" = "Use your teleporter and other support tools to jump right into your desired location, quickly leaving as though you were never there.",
						/obj/item/storage/box/syndie_kit/teleporter,
						/obj/item/clothing/gloves/color/black/krav_maga,
						/obj/item/clothing/glasses/thermal,
						/obj/item/pinpointer/advpinpointer,
						/obj/item/rcd/preloaded,
						/obj/item/storage/box/syndie_kit/space,
						/obj/item/autoimplanter/oneuse //Сделать с мезонами.
						/obj/item/encryptionkey/syndicate),
		"Grenadier" = list(grenadier
						"Name" = "\improper 'Grenadier' bundle",
						"Desc" = "A variety of grenades and pyrotechnics to ensure you can blast your way through any situation.",
						/obj/item/storage/belt/grenade/demolitionist,
						/obj/item/gun/projectile/automatic/pistol,
						/obj/item/ammo_box/magazine/m10mm,
						/obj/item/ammo_box/magazine/m10mm,
						/obj/item/ammo_box/magazine/m10mm/fire,
						/obj/item/ammo_box/magazine/m10mm/fire,
						/obj/item/clothing/shoes/chameleon/noslip,
						/obj/item/storage/box/syndie_kit/hardsuit,
						/obj/item/clothing/gloves/combat,
						/obj/item/card/id/syndicate,
						/obj/item/encryptionkey/syndicate),
	)
