#!/bin/bash
# Generate maps
tools/github-actions/nanomap-renderer minimap -w 2040 -h 2040 --disable icon-smoothing "./_maps/map_files/cyberiad/cyberiad.dmm"
tools/github-actions/nanomap-renderer minimap -w 2040 -h 2040 --disable icon-smoothing "./_maps/map_files/Delta/delta.dmm"
tools/github-actions/nanomap-renderer minimap -w 2040 -h 2040 --disable icon-smoothing "./_maps/map_files/cerestation/cerestation.dmm"
tools/github-actions/nanomap-renderer minimap -w 2040 -h 2040 --disable icon-smoothing "./_maps/map_files/celestation/celestation.dmm"
tools/github-actions/nanomap-renderer minimap -w 2040 -h 2040 --disable icon-smoothing "./_maps/map_files/nova/nova.dmm"
# Move and rename files so the game understands them
cd "data/nanomaps"
mv "cyberiad_nanomap_z1.png" "Cyberiad_nanomap_z1.png"
mv "delta_nanomap_z1.png" "Delta_nanomap_z1.png"
mv "cerestation_nanomap_z1.png" "Cerestation_nanomap_z1.png"
mv "celestation_nanomap_z1.png" "Celestation_nanomap_z1.png"
mv "celestation_nanomap_z2.png" "Celestation_nanomap_z2.png"
mv "celestation_nanomap_z3.png" "Celestation_nanomap_z3.png"
mv "nova_nanomap_z1.png" "Nova_nanomap_z1.png"
mv "nova_nanomap_z2.png" "Nova_nanomap_z2.png"
cd "../../"
cp "data/nanomaps/Cyberiad_nanomap_z1.png" "icons/_nanomaps"
cp "data/nanomaps/Delta_nanomap_z1.png" "icons/_nanomaps"
cp "data/nanomaps/Cerestation_nanomap_z1.png" "icons/_nanomaps"
cp "data/nanomaps/Celestation_nanomap_z1.png" "icons/_nanomaps"
cp "data/nanomaps/Celestation_nanomap_z2.png" "icons/_nanomaps"
cp "data/nanomaps/Celestation_nanomap_z3.png" "icons/_nanomaps"
cp "data/nanomaps/Nova_nanomap_z1.png" "icons/_nanomaps"
cp "data/nanomaps/Nova_nanomap_z2.png" "icons/_nanomaps"
