'Python':
  - changed-files:
      - any-glob-to-any-file: ['**/*.py']

'JavaScript':
  - changed-files:
      - any-glob-to-any-file: ['**/*.js']

'TypeScript':
  - changed-files:
      - any-glob-to-any-file: ['**/*.ts', '**/*.tsx']

'Rust':
  - changed-files:
      - any-glob-to-any-file: ['rust/**']

'SQL':
  - changed-files:
      - any-glob-to-any-file: ['SQL/**']

'TGUI':
  - changed-files:
      - any-glob-to-any-file: ['tgui/**', 'tgui-next/**']

'Спрайты':
  - changed-files:
      - any-glob-to-any-file: ['**/*.dmi']

'Изменение карты':
  - changed-files:
      - any-glob-to-any-file: ['**/*.dmm']

'Изменение конфига':
  - changed-files:
      - any-glob-to-any-file: ['config/**']

'Документация':
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']

'Звук':
  - changed-files:
      - any-glob-to-any-file: ['**/*.ogg']
