GLOBAL_LIST_INIT(ai_names, file2list("strings/names/ai.txt"))
GLOBAL_LIST_INIT(wizard_first, file2list("strings/names/wizardfirst.txt"))
GLOBAL_LIST_INIT(wizard_second, file2list("strings/names/wizardsecond.txt"))
GLOBAL_LIST_INIT(ninja_titles, file2list("strings/names/ninjatitle.txt"))
GLOBAL_LIST_INIT(ninja_names, file2list("strings/names/ninjaname.txt"))
GLOBAL_LIST_INIT(commando_names, file2list("strings/names/death_commando.txt"))
GLOBAL_LIST_INIT(first_names_male, file2list("strings/names/first_male.txt"))
GLOBAL_LIST_INIT(first_names_female, file2list("strings/names/first_female.txt"))
GLOBAL_LIST_INIT(last_names, file2list("strings/names/last.txt"))
GLOBAL_LIST_INIT(last_names_female, file2list("strings/names/last_female.txt"))
GLOBAL_LIST_INIT(clown_names, file2list("strings/names/clown.txt"))
GLOBAL_LIST_INIT(mime_names, file2list("strings/names/mime.txt"))
GLOBAL_LIST_INIT(golem_names, file2list("strings/names/golem.txt"))
GLOBAL_LIST_INIT(golem_male, file2list("strings/names/golem_male.txt"))
GLOBAL_LIST_INIT(golem_female, file2list("strings/names/golem_female.txt"))
GLOBAL_LIST_INIT(golem_neuter, file2list("strings/names/golem_neuter.txt"))
GLOBAL_LIST_INIT(megacarp_first_names, file2list("strings/names/megacarp1.txt"))
GLOBAL_LIST_INIT(megacarp_last_names, file2list("strings/names/megacarp2.txt"))

GLOBAL_LIST_INIT(verbs, file2list("strings/names/verbs.txt"))
GLOBAL_LIST_INIT(nouns, file2list("strings/names/nouns.txt"))
GLOBAL_LIST_INIT(adjectives, file2list("strings/names/adjectives.txt"))
GLOBAL_LIST_INIT(cocktails, file2list("strings/names/cocktails.txt"))
GLOBAL_LIST_INIT(locations, file2list("strings/names/locations.txt"))
GLOBAL_LIST_INIT(jobs, file2list("strings/names/jobs.txt"))
GLOBAL_LIST_INIT(dream_strings, file2list("strings/sleep/dreams.txt"))
GLOBAL_LIST_INIT(nightmare_strings, file2list("strings/sleep/nightmares.txt"))

GLOBAL_LIST_INIT(isp_whitelist, file2list("strings/names/isp_whitelist.txt"))
GLOBAL_LIST_INIT(isp_blacklist, file2list("strings/names/isp_blacklist.txt"))

GLOBAL_LIST_EMPTY(cached_ru_names)
//loaded on startup because of "
//would include in rsc if ' was used
