GLOBAL_LIST_EMPTY(preference_toggles)

GLOBAL_LIST_INIT(preference_toggle_groups, list(
	PREF_CATEGORY_GENERAL = PREFTOGGLE_CATEGORY_GENERAL,
	PREF_CATEGORY_LIVING = PREFTOGGLE_CATEGORY_LIVING,
	PREF_CATEGORY_GHOST = PREFTOGGLE_CATEGORY_GHOST,
	PREF_CATEGORY_ADMIN = PREFTOGGLE_CATEGORY_ADMIN,
))
