// Accounts core class - needs to be converted into a subsystem

GLOBAL_VAR(current_date_string)

#define AUT_ACCLST 1
#define AUT_ACCINF 2
#define AUT_ACCNEW 3

/obj/machinery/computer/account_database
	name = "Accounts Uplink Terminal"
	desc = "Получите доступ к журналам транзакций, данным учетной записи и всем видам других финансовых записей."
	icon_screen = "accounts"
	req_access = list(ACCESS_HOP, ACCESS_CAPTAIN, ACCESS_CENT_COMMANDER)
	light_color = LIGHT_COLOR_GREEN
	var/receipt_num
	var/machine_id = ""
	var/datum/money_account/detailed_account_view
	var/activated = TRUE
	var/const/fund_cap = 1000000
	/// Current UI page
	var/current_page = AUT_ACCLST
	/// Next time a print can be made
	var/next_print = 0

/obj/machinery/computer/account_database/Initialize(mapload)
	. = ..()
	// hehe kostil s tg
	// Why the fuck are these not in a subsystem? They are global variables for fucks sake
	// If someone ever makes a map without one of these consoles, the entire eco AND date system breaks
	// This upsets me a lot
	// AA Todo: SSeconomy

	if(!GLOB.current_date_string)
		GLOB.current_date_string = "[time2text(world.timeofday, "DD Month")], [GLOB.game_year]"

	machine_id = "[station_name()] Acc. DB #[GLOB.num_financial_terminals++]"

/obj/machinery/computer/account_database/proc/accounting_letterhead(report_name)
	var/datum/ui_login/L = ui_login_get()
	return {"
		<center><h1><b>[report_name]</b></h1></center>
		<center><small><i>[station_name()] Accounting Report</i></small></center>
		<u>Generated By:</u> [L?.id?.registered_name ? L.id.registered_name : UNKNOWN_NAME_RUS], [L?.id?.assignment ? L.id.assignment : UNKNOWN_STATUS_RUS]<br>
		<hr>
	"}

/obj/machinery/computer/account_database/attackby(obj/item/I, mob/user, params)
	if(user.a_intent == INTENT_HARM)
		return ..()

	if(ui_login_attackby(I, user))
		add_fingerprint(user)
		return ATTACK_CHAIN_BLOCKED_ALL

	return ..()

/obj/machinery/computer/account_database/attack_hand(mob/user)
	if(..())
		return TRUE
	if(issilicon(user))
		to_chat(user, span_warning("Обнаружен искусственный интеллект. Согласно регуляции \"Нанотрейзен\" №1023 вмешательство синтетических форм жизни в финансовые операции объекта запрещено."))
		return
	add_fingerprint(user)
	ui_interact(user)

/obj/machinery/computer/account_database/ui_interact(mob/user, datum/tgui/ui = null)
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "AccountsUplinkTerminal", name)
		ui.open()

/obj/machinery/computer/account_database/ui_data(mob/user)
	var/list/data = list()
	data["currentPage"] = current_page
	data["is_printing"] = (next_print > world.time)
	ui_login_data(data, user)
	if(data["loginState"]["logged_in"])
		switch(current_page)
			if(AUT_ACCLST)
				var/list/accounts = list()
				for(var/i in 1 to length(GLOB.all_money_accounts))
					var/datum/money_account/D = GLOB.all_money_accounts[i]
					accounts.Add(list(list(
						"account_number" = "[D.account_number]",
						"owner_name" = D.owner_name,
						"suspended" = D.suspended ? "SUSPENDED" : "Active",
						"money" = "[D.money]", // needs to be strings because of TGUI localeCompare
						"account_index" = i)))

				data["accounts"] = accounts

			if(AUT_ACCINF)
				data["account_number"] = detailed_account_view.account_number
				data["owner_name"] = detailed_account_view.owner_name
				data["money"] = detailed_account_view.money
				data["suspended"] = detailed_account_view.suspended

				var/salary_mod = 0
				var/datum/subscription/salary_modifier/this_modifier = find_subscription_salary_modifier_spec(detailed_account_view.owner_name, /datum/subscription/salary_modifier)

				if(this_modifier)
					salary_mod = this_modifier.modifier;

				data["salary_modifier"] = salary_mod

				var/list/transactions = list()
				for(var/datum/transaction/T in detailed_account_view.transaction_log)
					transactions.Add(list(list(
						"date" = T.date,
						"time" = T.time,
						"target_name" = T.target_name,
						"purpose" = T.purpose,
						"amount" = T.amount,
						"source_terminal" = T.source_terminal)))

				data["transactions"] = transactions
	return data

/obj/machinery/computer/account_database/ui_act(action, list/params)
	if(..())
		return

	. = TRUE

	if(ui_login_act(action, params))
		return

	if(!ui_login_get().logged_in)
		return

	switch(action)
		if("view_account_detail")
			var/index = text2num(params["index"])
			if(index && index > 0 && index <= length(GLOB.all_money_accounts))
				detailed_account_view = GLOB.all_money_accounts[index]
				current_page = AUT_ACCINF

		if("back")
			detailed_account_view = null
			current_page = AUT_ACCLST

		if("toggle_suspension")
			if(detailed_account_view)
				detailed_account_view.suspended = !detailed_account_view.suspended
				if(detailed_account_view.suspended)
					SEND_SIGNAL(detailed_account_view, COMSIG_ACCOUNT_SUSPENDED)
				else
					SEND_SIGNAL(detailed_account_view, COMSIG_ACCOUNT_UNSUSPENDED)

		if("create_new_account")
			current_page = AUT_ACCNEW

		if("finalise_create_account")
			var/account_name = params["holder_name"]
			var/starting_funds = max(text2num(params["starting_funds"]), 0)
			if(!account_name || !starting_funds)
				return

			starting_funds = clamp(starting_funds, 0, GLOB.station_account.money) // Not authorized to put the station in debt.
			starting_funds = min(starting_funds, fund_cap) // Not authorized to give more than the fund cap.

			var/datum/money_account/M = create_account(account_name, starting_funds, src)
			if(starting_funds > 0)
				GLOB.station_account.charge(starting_funds, null, "New account activation", "", "New account activation", M.owner_name)
			M.insurance_type = INSURANCE_TYPE_BUDGETARY
			M.insurance = INSURANCE_NONE

			current_page = AUT_ACCLST

		if("print_records")
			// Anti spam measures
			if(next_print > world.time)
				to_chat(usr, "<span class='warning'>The printer is busy spooling. It will be ready in [(next_print - world.time) / 10] seconds.")
				return
			var/text
			playsound(loc, 'sound/goonstation/machines/printer_thermal.ogg', 50, TRUE)
			var/obj/item/paper/P = new(loc)
			P.name = "financial account list"
			text = {"
				[accounting_letterhead("Financial Account List")]

				<table>
					<thead>
						<tr>
							<td>Account Number</td>
							<td>Holder</td>
							<td>Balance</td>
							<td>Status</td>
						</tr>
					</thead>
					<tbody>
			"}

			for(var/i in 1 to length(GLOB.all_money_accounts))
				var/datum/money_account/D = GLOB.all_money_accounts[i]
				text += {"
						<tr>
							<td>#[D.account_number]</td>
							<td>[D.owner_name]</td>
							<td>$[D.money]</td>
							<td>[D.suspended ? "Suspended" : "Active"]</td>
						</tr>
				"}

			text += {"
					</tbody>
				</table>
			"}

			P.info = text
			visible_message(span_notice("[src] prints out a report."))
			next_print = world.time + 30 SECONDS

		if("print_account_details")
			// Anti spam measures
			if(next_print > world.time)
				to_chat(usr, "<span class='warning'>The printer is busy spooling. It will be ready in [(next_print - world.time) / 10] seconds.")
				return
			var/text
			playsound(loc, 'sound/goonstation/machines/printer_thermal.ogg', 50, TRUE)
			var/obj/item/paper/P = new(loc)
			P.name = "account #[detailed_account_view.account_number] details"
			var/title = "Account #[detailed_account_view.account_number] Details"
			text = {"
				[accounting_letterhead(title)]
				<u>Holder:</u> [detailed_account_view.owner_name]<br>
				<u>Balance:</u> $[detailed_account_view.money]<br>
				<u>Status:</u> [detailed_account_view.suspended ? "Suspended" : "Active"]<br>
				<u>Transactions:</u> ([length(detailed_account_view.transaction_log)])<br>
				<table>
					<thead>
						<tr>
							<td>Timestamp</td>
							<td>Target</td>
							<td>Reason</td>
							<td>Value</td>
							<td>Terminal</td>
						</tr>
					</thead>
					<tbody>
				"}

			for(var/datum/transaction/T in detailed_account_view.transaction_log)
				text += {"
							<tr>
								<td>[T.date] [T.time]</td>
								<td>[T.target_name]</td>
								<td>[T.purpose]</td>
								<td>[T.amount]</td>
								<td>[T.source_terminal]</td>
							</tr>
					"}

			text += {"
					</tbody>
				</table>
				"}

			P.info = text
			visible_message(span_notice("[src] prints out a report."))
			next_print = world.time + 30 SECONDS

		if("set_salary_modifier")
			var/sub_type = /datum/subscription/salary_modifier
			var/owner_name = params["owner_name"]
			var/datum/money_account/sub_acc = get_account_with_name(owner_name)

			if(!sub_acc)
				to_chat(usr, span_danger("Аккаунт не найден."))
				return

			var/list/extra_params = list()
			var/salary_modifier = text2num(params["modifier"])
			extra_params["modifier"] = salary_modifier

			var/datum/subscription/salary_modifier/target = find_subscription_salary_modifier_spec(owner_name, sub_type)

			if(!target)
				create_subscription(sub_acc, sub_type, extra_params)
				ui_interact(usr)
				return

			if(salary_modifier == 0)
				target.cancel()
				target.modifier = 0
				to_chat(usr, span_notice("Модификатор сброшен."))
				ui_interact(usr)
				return

			target.modifier = salary_modifier
			var/datum/job/user_job = sub_acc.linked_job
			var/base_paycheck = user_job.paycheck
			target.cost = abs(base_paycheck * salary_modifier / 100)
			target.active = TRUE

			if(salary_modifier < 0)
				target.recipient_account = GLOB.station_account
				target.subscriber_account = sub_acc
			else
				target.recipient_account = sub_acc
				target.subscriber_account = GLOB.station_account

			to_chat(usr, span_notice("Модификатор обновлён: [salary_modifier]%."))
			ui_interact(usr)

#undef AUT_ACCLST
#undef AUT_ACCINF
#undef AUT_ACCNEW
