#define HASBIT(CONTAINER, FLAG)     ((CONTAINER) & (FLAG))

#define SETBIT(CONTAINER, FLAG)     (CONTAINER |= (FLAG))

#define CLEARBIT(CONTAINER, FLAG)   (CONTAINER &= ~(FLAG))

#define TOGGLEBIT(CONTAINER, FLAG)  (CONTAINER ^= (FLAG))
