/// These values are used when logging user-initiated announcements.
#define ANNOUNCE_KIND_DEFAULT		"Announcement"
#define ANNOUNCE_KIND_MINOR			"Minor Announcement"
#define ANNOUNCE_KIND_PRIORITY		"Priority Announcement"
#define ANNOUNCE_KIND_SECURITY		"Security Announcement"
#define ANNOUNCE_KIND_MAJOR			"NAS Trurl Update"
#define ANNOUNCE_KIND_EVENT			"NAS Trurl Update"  // Intentionally the same as above
#define ANNOUNCE_KIND_AI			"A.I. Announcement"

/// Security code name.
#define SECURITY_CODE_GREEN			"green"
#define SECURITY_CODE_BLUE			"blue"
#define SECURITY_CODE_RED			"red"
#define SECURITY_CODE_GAMMA			"gamma"
#define SECURITY_CODE_EPSILON		"epsilon"
#define SECURITY_CODE_DELTA			"delta"

/// We separate the title define from logging.
#define ANNOUNCE_DEFAULT_RU			"Объявление."
#define ANNOUNCE_MINOR_RU			"Небольшое объявление."
#define ANNOUNCE_PRIORITY_RU		"Приоритетное оповещение."
#define ANNOUNCE_SECURITY_RU		"Объявление о безопасности."
#define ANNOUNCE_MAJOR_RU			"АКН Трурль обновление."
#define ANNOUNCE_EVENT_RU			"АКН Трурль обновление."
#define ANNOUNCE_AI_RU				"Объявление ИИ."

/// Define of other titles.
#define ANNOUNCE_BIOHAZARD_RU		"Биологическая угроза."
#define ANNOUNCE_ANOMALY_RU			"Предупреждение об аномалии."
#define ANNOUNCE_PARANORMAL_RU		"Паранормальная активность."
#define ANNOUNCE_CCPARANORMAL_RU	"Отдел Центрального командования по делам высших измерений."
#define ANNOUNCE_METEOR_RU			"Метеориты."
#define ANNOUNCE_NIGHTSHIFT_RU		"Автоматизированная система освещения."
#define ANNOUNCE_BLUESPACETAP_RU	"Сбой Блюспейс-сборщика."
#define ANNOUNCE_ERT_ACTIVATE_RU	"Активирован протокол ОБР."
#define ANNOUNCE_ERT_UNAVAIL_RU		"ОБР недоступен."
#define ANNOUNCE_ERT_ONWAY_RU		"ОБР в пути."
#define ANNOUNCE_CCDEMOTE_RU		"Приказ Центрального командования об увольнение."
#define ANNOUNCE_DECLAREWAR_RU		"Объявление войны."
#define ANNOUNCE_WILDNATURE_RU		"Отдел Центрального командования по изучению дикой природы."
#define ANNOUNCE_UNID_LIFEFORMS_RU	"Неопознанные формы жизни."
#define ANNOUNCE_MALF_RU			"ОШИБКА ОШИБКА $0ШБК$!А41.%%!!(%$^^__+ @#Ш0E4"
#define ANNOUNCE_NUCLEARCODES_RU	"Запрошены коды активации ядерной боеголовки."
#define ANNOUNCE_CCMSG_RU			"Сообщение Центрального командования."
#define ANNOUNCE_SYSERROR_RU		"Системный сбой."
#define ANNOUNCE_CAPITAL_DEFOLT_RU	"Дефолт станции."
#define ANNOUNCE_CAPITAL_REPAY_RU	"Возобновление выплат."
#define ANNOUNCE_SOLAR_FLARE_RU		"Солнечная вспышка."
#define ANNOUNCE_SECRETMSG_RU		"Входящее засекреченное сообщение."
#define ANNOUNCE_APC_CRIT_RU		"Критический сбой системы питания."
#define ANNOUNCE_APC_REPAIR_RU		"Система питания восстановлена."
#define ANNOUNCE_ROGUE_DRONE_RU		"Сбойные дроны."
#define ANNOUNCE_HONKANOMALY_RU		"Предупреждение о Хонканомалии."
