#define REPRODUCTIONS_TO_MATURE 3
#define REPRODUCTIONS_TO_ADULT 6
#define REPRODUCTIONS_TO_ELDER 10
#define HEAD_FOCUS_COST 9
#define TORSO_FOCUS_COST 15
#define HANDS_FOCUS_COST 5
#define LEGS_FOCUS_COST 10
#define SCALING_MAX_CHEM 355
#define SCALING_CHEM_GAIN 15
#define BORER_RANK_YOUNG /datum/borer_rank/young
#define BORER_RANK_MATURE /datum/borer_rank/mature
#define BORER_RANK_ADULT /datum/borer_rank/adult
#define BORER_RANK_ELDER /datum/borer_rank/elder
