#define CONTRACT_POWER "Сила"
#define CONTRACT_WEALTH "Богатство"
#define CONTRACT_PRESTIGE "Престиж"
#define CONTRACT_MAGIC "Магия"
#define CONTRACT_REVIVE "Воскрешение"
#define CONTRACT_KNOWLEDGE "Знание"
#define CONTRACT_UNWILLING "Безвозмездный контракт"
#define CONTRACT_FRIENDSHIP "Дружба"
#define CONTRACT_YOUTH "Вечная молодость"
// FIXME: Implement these
#define CONTRACT_ETALENT "Engineering Talent"
#define CONTRACT_CTALENT "Chemistry Talent"
#define CONTRACT_RETURNDEAD "Return Dead"
#define CONTRACT_AUGMENT "Cybernetic Augmentations"
#define CONTRACT_CANDY "Endless Candy"
#define CONTRACT_ECHANCE "An Extra Chance"
#define CONTRACT_ATECH "Advanced Technology"
#define CONTRACT_DEVILSMACHINE "Devil's Machinery"
#define CONTRACT_FOOD "Food"
#define CONTRACT_SPACE "Space Gear"
#define CONTRACT_CALAMITY "Calamity"
