//criminal status defines
#define SEC_RECORD_STATUS_NONE "Нет"
#define SEC_RECORD_STATUS_ARREST "*Арест*"
#define SEC_RECORD_STATUS_EXECUTE "*Казнь*"
#define SEC_RECORD_STATUS_INCARCERATED "Заключённый"
#define SEC_RECORD_STATUS_RELEASED "Освобождённый"
#define SEC_RECORD_STATUS_PAROLLED "Условно-досрочно освобождённый"
#define SEC_RECORD_STATUS_DEMOTE "Понижение"
#define SEC_RECORD_STATUS_SEARCH "Обыскать"
#define SEC_RECORD_STATUS_MONITOR "Контролировать"
