//criminal status defines
#define SEC_RECORD_STATUS_NONE "None"
#define SEC_RECORD_STATUS_ARREST "*Arrest*"
#define SEC_RECORD_STATUS_EXECUTE "*Execute*"
#define SEC_RECORD_STATUS_INCARCERATED "Incarcerated"
#define SEC_RECORD_STATUS_RELEASED "Released"
#define SEC_RECORD_STATUS_PAROLLED "Parolled"
#define SEC_RECORD_STATUS_DEMOTE "Demote"
#define SEC_RECORD_STATUS_SEARCH "Search"
#define SEC_RECORD_STATUS_MONITOR "Monitor"

#define SEC_STATUS_NONE "none"
#define SEC_STATUS_ARREST "arrest"
#define SEC_STATUS_EXECUTE "execute"
#define SEC_STATUS_INCARCERATED "incarcerated"
#define SEC_STATUS_RELEASED "released"
#define SEC_STATUS_PAROLLED "parolled"
#define SEC_STATUS_DEMOTE "demote"
#define SEC_STATUS_SEARCH "search"
#define SEC_STATUS_MONITOR "monitor"

#define LAW_LEVEL_BASE 0
#define LAW_LEVEL_HEAD 1
#define LAW_LEVEL_SEC 2
#define LAW_LEVEL_WARDEN 3
#define LAW_LEVEL_HOS 4
#define LAW_LEVEL_CAPTAIN 5
#define LAW_LEVEL_MAGISTRATE 6
#define LAW_LEVEL_RESPONSE_TEAM 7
#define LAW_LEVEL_CENTCOMM 8
