#define CUSTOM_OUTFIT_DEFAULT_NAME "Custom Outfit"
#define CUSTOM_OUTFIT_LIMB_STATUS_AMPUTATED "amputated"
#define CUSTOM_OUTFIT_LIMB_STATUS_PROSTHETIC "prosthetic"
#define CUSTOM_OUTFIT_LIMB_STATUS_AUGMENTED "augmented"
#define CUSTOM_OUTFIT_MAX_REAGENT_AMOUNT 100
