#define EVENT_LEVEL_MUNDANE 1
#define EVENT_LEVEL_MODERATE 2
#define EVENT_LEVEL_MAJOR 3
#define EVENT_LEVEL_NONE 4

// Common events
#define EVENT_ABDUCTORS "Визит абдукторов"
#define EVENT_ACCOUNT_HACKED "Взлом аккаунта"
#define EVENT_AIRLOCK_MALFUNCTION "Сбой работы шлюзов"
#define EVENT_ANOMALY "Аномалия"
#define EVENT_APC_OVERLOAD "Перегрузка ЛКП"
#define EVENT_APC_SHORTAGE "Замыкание ЛКП"
#define EVENT_APPENDIX "Аппендицит"
#define EVENT_BLOB "Блоб"
#define EVENT_BORER_INFESTATION "Нашествие бореров"
#define EVENT_CARP_INFESTATION "Скопление карпов"
#define EVENT_CARP_MIGRATION "Миграция карпов"
#define EVENT_CURSED_PIANO "Проклятое фортепиано"
#define EVENT_DIGITAL_VIRUS "Цифровой вирус"
#define EVENT_DIMENSIONAL_TEAR "Пространственный разрыв"
#define EVENT_DISEASE_OUTBREAK "Вспышка болезни"
#define EVENT_DRIFTING_CONTRACTOR "Дрейфующий Контрактник"
#define EVENT_DRONE_MALFUNCTION "Сбойные дроны"
#define EVENT_ECONOMICAL_NEWS "Новости экономики"
#define EVENT_ELECTRICAL_STORM "Электрический шторм"
#define EVENT_FALSE_ALARM "Ложная тревога"
#define EVENT_HEADCRABS "Хедкрабы"
#define EVENT_HEADSLUG_INFESTATION "Нашествие хедслагов"
#define EVENT_HONKANOMALY "Хонканомалия"
#define EVENT_IMMOVABLE_ROD "Несдвигаемый стержень"
#define EVENT_ION_TYPHOON "Ионный тайфун"
#define EVENT_KOI_MIGRATION "Миграция кои"
#define EVENT_LAUGHTER_DEMON "Демон Смеха"
#define EVENT_LONE_OPERATIVE "Ядерный оперативник"
#define EVENT_MASS_HALLUCINATION "Массовые галлюцинации"
#define EVENT_MEAT_WAVE "Мясной дождь"
#define EVENT_METEOR_WAVE "Метеорный дождь"
#define EVENT_METEOR_WAVE_HUGE "Метеорный вал"
#define EVENT_MONEY_LOTTERY "Денежная лотерея"
#define EVENT_MORPH "Спавн морфа"
#define EVENT_NOTHING "Ничего"
#define EVENT_PDA_SPAM "Спам на КПК"
#define EVENT_PEST_INFESTATION "Нашествие вредителей"
#define EVENT_PRISON_BREAK "Побег"
#define EVENT_PULSE_DEMON "Pulse Demon Infiltration"
#define EVENT_RADIATION_STORM "Радиационный шторм"
#define EVENT_RANDOMENSIONAL_TEAR "Рандомысленный разрыв"
#define EVENT_REVENANT "Ревенант"
#define EVENT_SCARCE_NEWS "Скудные новости"
#define EVENT_SENTIENT_CREATURE "Сознание"
#define EVENT_SHADOW_DEMON "Теневой Демон"
#define EVENT_SLAUGHTER_DEMON "Демон Резни"
#define EVENT_SOLAR_FLARE "Солнечная вспышка"
#define EVENT_SPACE_DRAGON "Космический Дракон"
#define EVENT_SPACE_DUST "Space Dust"
#define EVENT_SPACE_NINJA "Космический ниндзя"
#define EVENT_SPACEVINE "Космолоза"
#define EVENT_SPIDER_INFESTATION "Нашествие пауков"
#define EVENT_STANDARD_NEWS "Обычные новости"
#define EVENT_SWARMERS "Спавн свармеров"
#define EVENT_TELECOMMS_MALFUNCTION "Телекоммуникационный сбой"
#define EVENT_TERROR_SPIDER "Пауки Ужаса"
#define EVENT_TRADERS "Торговцы"
#define EVENT_VENT_CLOG "Отходы из вытяжек"
#define EVENT_VOX_RAIDERS "Воксы рейдеры"
#define EVENT_WALL_FUNGUS "Стенной грибок"
#define EVENT_WORMHOLES "Червоточины"
#define EVENT_XENOMORPH_INFESTATION "Заражение ксеноморфами"

// Events from bluespace rift scanner(BRS) station goal
#define EVENT_BRS_TELEPORT_LIVINGS "Телепортация живых"
#define EVENT_BRS_TELEPORT_LIVINGS_FAR "Телепортация живых далеко"
#define EVENT_BRS_SWAP_LIVINGS "Поменять местами живых"
#define EVENT_BRS_EXPLOSIONS "Взрывы"
#define EVENT_BRS_EMP "ЭМИ"
#define EVENT_BRS_FLASHES "Вспышки"
#define EVENT_BRS_SMOKE "Дым"
#define EVENT_BRS_SPARKS "Искры"
#define EVENT_BRS_CHEM_EXPLOSIONS "Химические взрывы"
#define EVENT_BRS_DANGEROUS_CHEM_EXPLOSIONS "Опасные химические взрывы"
#define EVENT_BRS_CLOWN_CHEM_EXPLOSIONS "Клоунские химические взрывы"
#define EVENT_BRS_STAIN_FLOOR "Испачкать пол"
#define EVENT_BRS_SNOW "Снег"
