#define INSURANCE_NONE          	0
#define INSURANCE_BUDGETARY     	1000
#define INSURANCE_STANDART      	3000
#define INSURANCE_EXTENDED      	6000
#define INSURANCE_DELUXE			10000
#define INSURANCE_NT_SPECIAL		100000

#define REQ_INSURANCE_BRUT      	1.5
#define REQ_INSURANCE_BURN      	1.5
#define REQ_INSURANCE_OXY       	0.5
#define REQ_INSURANCE_TOX       	0.5
#define REQ_INSURANCE_ORGAN     	1
#define REQ_INSURANCE_RAD       	1
#define REQ_INSURANCE_CLONE     	2
#define REQ_INSURANCE_BLOOD     	2 // 1% of max blood
#define REQ_INSURANCE_INTBLEED  	150
#define REQ_INSURANCE_BONE      	150
#define REQ_INSURANCE_LOST_ORGAN	300
#define REQ_INSURANCE_LOST_LIMB  	300
#define REQ_INSURANCE_CRIT      	250
#define REQ_INSURANCE_DEATH      	500
