#define LAUNCHER_CKEY_PREFIX "STM"

#define LAUNCHER_UNLINKED 0
#define LAUNCHER_PENDING 1
#define LAUNCHER_VERIFIED 2

#define LAUNCHER_VERIFY_TIMEOUT (15 SECONDS)

#define DISCORD_TOKEN_LENGTH 32

#define LAUNCHER_NICKNAME_MAX_LEN 32

#define LAUNCHER_LINK_NONE 0
#define LAUNCHER_LINK_PENDING 1
#define LAUNCHER_LINK_APPROVED 2
#define LAUNCHER_LINK_REJECTED 3
