#define LAZY_TEMPLATE_KEY_BINGLE_PIT "LT_BINGLEPIT"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_RAGECAGE "LT_DM_RAGECAGE"

#define LAZY_TEMPLATE_KEY_LIST_ALL(...) list( \
	"Bingle Pit" = LAZY_TEMPLATE_KEY_BINGLE_PIT, \
	"Rage Cage" = LAZY_TEMPLATE_KEY_DEATHMATCH_RAGECAGE, \
)
