#define LAZY_TEMPLATE_KEY_BINGLE_PIT "LT_BINGLEPIT"
#define LAZY_TEMPLATE_KEY_MANSUS_BACKDOOR "LT_MANSUSBACKDOOR"

#define LAZY_TEMPLATE_KEY_LIST_ALL(...) list( \
	"Bingle Pit" = LAZY_TEMPLATE_KEY_BINGLE_PIT, \
	"Mansus Backdoor" = LAZY_TEMPLATE_KEY_MANSUS_BACKDOOR, \
)
