#define LAZY_TEMPLATE_KEY_BINGLE_PIT "LT_BINGLEPIT"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_RAGECAGE "LT_DM_RAGECAGE"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_OSHA_VIOLATOR "LT_DM_OSHA_VIOLATOR"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_ARENA_STATION "LT_DM_ARENA_STATION"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_BACKALLEY "LT_DM_BACKALLEY"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_FINAL_DESTINATION "LT_DM_FINAL_DESTINATION"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_INSTAGIB "LT_DM_INSTAGIB"
#define LAZY_TEMPLATE_KEY_DEATHMATCH_LATTICE_BATTLE "LT_DM_LATTICE_BATTLE"

#define LAZY_TEMPLATE_KEY_LIST_ALL(...) list( \
	"Bingle Pit" = LAZY_TEMPLATE_KEY_BINGLE_PIT, \
	"Rage Cage" = LAZY_TEMPLATE_KEY_DEATHMATCH_RAGECAGE, \
	"OSHA Violator" = LAZY_TEMPLATE_KEY_DEATHMATCH_OSHA_VIOLATOR, \
	"Arena Station" = LAZY_TEMPLATE_KEY_DEATHMATCH_ARENA_STATION, \
	"Back Alley" = LAZY_TEMPLATE_KEY_DEATHMATCH_BACKALLEY, \
	"Final Destination" = LAZY_TEMPLATE_KEY_DEATHMATCH_FINAL_DESTINATION, \
	"Insta Gib" = LAZY_TEMPLATE_KEY_DEATHMATCH_INSTAGIB, \
	"Lattice Battle" = LAZY_TEMPLATE_KEY_DEATHMATCH_LATTICE_BATTLE, \
)
