#define LOGISTICS_MODE_SEND 1
#define LOGISTICS_MODE_RECEIVE 2

#define LOGISTICS_REQUEST_PENDING 0
#define LOGISTICS_REQUEST_ACTIVE 1
#define LOGISTICS_REQUEST_PAUSED 2
#define LOGISTICS_REQUEST_COMPLETE 3
#define LOGISTICS_REQUEST_CANCELLED 4

#define LOGISTICS_MAX_LOGS 50
#define LOGISTICS_MAX_IN_FLIGHT 16
#define LOGISTICS_MAX_STEPS 1000
#define LOGISTICS_HOLDER_MOVE_DELAY 1
#define LOGISTICS_MAX_ARCHIVE 100
#define LOGISTICS_MAX_SHIPMENT_ITEMS 25
#define LOGISTICS_SHIPMENT_INTERVAL (5 SECONDS)
#define PIPE_LOGISTICS_STRAIGHT 200
#define PIPE_LOGISTICS_BENT 201
#define PIPE_LOGISTICS_JUNCTION_RIGHT 202
#define PIPE_LOGISTICS_JUNCTION_LEFT 203
#define PIPE_LOGISTICS_Y_JUNCTION 204
#define PIPE_LOGISTICS_TRUNK 205

#define LOGISTICS_NET_COLORS list("#e74c3c", "#e67e22", "#f1c40f", "#2ecc71", "#1abc9c", "#3498db", "#9b59b6", "#e91e63", "#00bcd4", "#8bc34a")
