#define OVERMAP_EDGE 2
#define OVERMAP_DEFAULT_SIZE 20

#define OVERMAP_VIEW_PAD 1
#define OVERMAP_MOVE_RESOLUTION 0.001

#define OVERMAP_TILE_EDGE 0.5

#define OVERMAP_SPEED_DISPLAY_SCALE 1000
#define OVERMAP_DISPLAY_SPEED(speed) ((speed) * OVERMAP_SPEED_DISPLAY_SCALE)
#define OVERMAP_FROM_DISPLAY(display) ((display) / OVERMAP_SPEED_DISPLAY_SCALE)

#define OVERMAP_SECTOR_KIND_STATION "station"
#define OVERMAP_SECTOR_KIND_SERVICE "service"
#define OVERMAP_SECTOR_KIND_WILDERNESS "wilderness"
#define OVERMAP_SECTOR_KIND_RUIN "ruin"

#define OVERMAP_SECTOR_ID_STATION "station"
#define OVERMAP_SECTOR_ID_SERVICE "service"
#define OVERMAP_SECTOR_ID_WILDERNESS_A "wilderness_a"
#define OVERMAP_SECTOR_ID_WILDERNESS_B "wilderness_b"

#define OVERMAP_SITE_CENTCOM "centcom"
#define OVERMAP_SITE_NINJA "ninja"
#define OVERMAP_SITE_SYNDICATE "syndicate"
#define OVERMAP_SITE_TRADER "trader"
#define OVERMAP_SITE_VOX "vox"
#define OVERMAP_HOST_STATION "station"
#define OVERMAP_HOST_LAVALAND "lavaland"
#define OVERMAP_HOST_TAIPAN "taipan"
#define OVERMAP_SITE_TAIPAN "taipan_site"

#define OVERMAP_SECTOR_STATION_SIZE 20
#define OVERMAP_SECTOR_SERVICE_SIZE 16
#define OVERMAP_SECTOR_WILDERNESS_SIZE 24

#define OVERMAP_LAVALAND_FOOTPRINT 4
#define OVERMAP_STATION_MIN_SEPARATION 4
#define OVERMAP_STATION_MAX_SEPARATION 6
#define OVERMAP_TAIPAN_EDGE_MIN 2
#define OVERMAP_TAIPAN_EDGE_MAX 3

#define SHIP_SPEED_SLOW (1 / (40 SECONDS))
#define SHIP_SPEED_FAST (1 / (5 SECONDS))

#define OVERMAP_VESSEL_STATION (1<<0)
#define OVERMAP_VESSEL_SHUTTLE (1<<1)
#define OVERMAP_VESSEL_WARP (1<<2)
#define OVERMAP_VESSEL_POD (1<<3)

#define OVERMAP_STATUS_DOCKED "docked"
#define OVERMAP_STATUS_OVERMAP "overmap"
#define OVERMAP_STATUS_TRANSIT "transit"

#define OVERMAP_ACCESS_PUBLIC (1<<0)
#define OVERMAP_ACCESS_CENTCOM (1<<1)
#define OVERMAP_ACCESS_SYNDICATE (1<<2)

#define OVERMAP_SANITIZE_SPEED(speed, max_speed) (sign(speed) * clamp(abs(speed), 0, max_speed))

#define OVERMAP_KIND_STATION "station"
#define OVERMAP_KIND_SHUTTLE "shuttle"
#define OVERMAP_KIND_POD "pod"
#define OVERMAP_KIND_PORTAL "portal"
#define OVERMAP_KIND_PLANET "planet"
#define OVERMAP_KIND_RUIN "ruin"
#define OVERMAP_KIND_HAZARD "hazard"
#define OVERMAP_KIND_RELAY "relay"
#define OVERMAP_KIND_OTHER "other"

#define OVERMAP_IFF_GLOBAL "global"
#define OVERMAP_IFF_CENTCOM "centcom"
#define OVERMAP_IFF_SYNDICATE "syndicate"
#define OVERMAP_IFF_HIJACK "hijack_null"
#define OVERMAP_IFF_KEY_LEN 8

#define OVERMAP_HYPERSPACE_HULL_KEEP 2
#define OVERMAP_HYPERSPACE_BORDER_KILL 3
#define OVERMAP_HYPERSPACE_LIMB_BRUTE 2
#define OVERMAP_HYPERRELAY_JUMP_TIME (10 SECONDS)

#define OVERMAP_PROGRAMMED_CRUISE 20
#define OVERMAP_PROGRAMMED_WINDUP (10 SECONDS)
#define OVERMAP_PROGRAMMED_EMAG_TIME (10 MINUTES)
#define OVERMAP_PROGRAMMED_EMAG_EMERGENCY_TIME (30 MINUTES)
#define OVERMAP_PROGRAMMED_EMAG_CD (10 MINUTES)

#define OVERMAP_PROG_WINDUP "windup"
#define OVERMAP_PROG_UNDOCK "undock"
#define OVERMAP_PROG_FLY "fly"
#define OVERMAP_PROG_JUMP "jump"
#define OVERMAP_PROG_DOCK "dock"

#define OVERMAP_VIEW_WIDTH 19
#define OVERMAP_VIEW_HEIGHT 15
#define OVERMAP_CONSOLE_MAP_PX_W 608
#define OVERMAP_CONSOLE_MAP_PX_H 480
#define OVERMAP_PROGRAMMED_DOCK_RETRY (15 SECONDS)
#define OVERMAP_PROGRAMMED_DOCK_TRIES 3

#define OVERMAP_DOCK_MANUAL "manual"
#define OVERMAP_DOCK_RESERVED "reserved"

#define OVERMAP_DOCK_Z_STATION "station"

#define OVERMAP_DOCK_Z_MINING "mining"

#define OVERMAP_DOCK_Z_SERVICE "service"

#define OVERMAP_DOCK_Z_RUIN "ruin"

#define OVERMAP_DOCK_Z_TAIPAN "taipan"

#define OVERMAP_DOCK_ID_EDGE "__overmap_edge"

#define OVERMAP_DOCK_ID_CUSTOM "__overmap_custom"
#define OVERMAP_DOCK_NEED_CUSTOM_PICK "need_custom_pick"

#define OVERMAP_RUIN_QUADRANTS 4

#define OVERMAP_RUIN_REGION_SIZE 96

#define OVERMAP_RUIN_REGION_PAD 1

#define OVERMAP_RESERVED_MEDIUM_Z 2
#define OVERMAP_RESERVED_MEDIUM_CELLS_PER_Z 4
#define OVERMAP_RESERVED_LARGE_Z 1
#define OVERMAP_RESERVED_TRANSIT_Z 1

#define OVERMAP_RUIN_WRAP_INSET 10

#define OVERMAP_TILE_VISUAL_SCALE 2

#define OVERMAP_HEADING_SPEED_MIN 3
#define OVERMAP_SPEED_STOPPED(speed) (OVERMAP_DISPLAY_SPEED(speed) < OVERMAP_HEADING_SPEED_MIN)

#define OVERMAP_CRUISE_MIN 1
#define OVERMAP_CRUISE_MAX 45
#define OVERMAP_CRUISE_DEFAULT 5

#define OVERMAP_NAV_MARKER_STATE "object"

#define OVERMAP_ICON_FILE 'icons/overmap/overmap.dmi'
#define OVERMAP_NUMBERS_ICON_FILE 'icons/overmap/overmap_numbers.dmi'
#define OVERMAP_PLANET_ICON_FILE 'icons/overmap/overmap_128.dmi'

#define OVERMAP_LOCAL_GHOST_ALPHA 110

#define OVERMAP_SENSOR_TIME_DELAY (0.2 SECONDS)
#define OVERMAP_SENSOR_PEEL_INTERVAL (3 SECONDS)
#define OVERMAP_SENSOR_PEEL_IN (0.5 SECONDS)
#define OVERMAP_SENSOR_PEEL_HOLD (1 SECONDS)
#define OVERMAP_SENSOR_PEEL_OUT (2.5 SECONDS)
#define OVERMAP_SENSOR_PEEL_FAR_ALPHA 128
#define OVERMAP_SENSOR_MEMORY_TIME (30 SECONDS)
#define OVERMAP_SENSOR_SCAN_TIME (10 SECONDS)
#define OVERMAP_SENSOR_RANGE_ICON 'icons/overmap/sierra_overmap.dmi'

#define OVERMAP_UNKNOWN_NAME "Неизвестный объект"

#define OVERMAP_SENSOR_LONG_VIEW 7
#define OVERMAP_SENSOR_SHORT_VIEW 2
#define OVERMAP_HELM_VIEW 4
#define OVERMAP_SENSOR_PING_RANGE 1
#define OVERMAP_SENSOR_PING_DURATION (30 SECONDS)
#define OVERMAP_SENSOR_PING_COOLDOWN (90 SECONDS)
#define OVERMAP_SENSOR_SCAN_MAX_SIZE 100
#define OVERMAP_SENSOR_SCAN_PAD 3

#define OVERMAP_SENSOR_SCAN_VIEW_PX 350

#define OVERMAP_HELM_MAP_PX 268
#define OVERMAP_DOCK_PREVIEW_MAX 21
#define OVERMAP_ICON_STATION "ship"
#define OVERMAP_ICON_SHUTTLE_C "shuttle_c"
#define OVERMAP_ICON_SHUTTLE_A "shuttle_a"
#define OVERMAP_ICON_POD "pod"

#define OVERMAP_POD_WRAP_RANGE 10

#define OVERMAP_POD_BEACON_RANGE 5

#define OVERMAP_POD_HYPERSPACE_SIZE 4

#define OVERMAP_POD_TRANSIT_BORDER 8

#define OVERMAP_POD_DOCK_KEEP 6
#define OVERMAP_POD_UNDOCK_DELAY (5 SECONDS)
#define OVERMAP_POD_MASS 100

#define OVERMAP_POD_THRUST 1
#define OVERMAP_ENGINE_SMALL_THRUST (OVERMAP_POD_THRUST * 4)
#define OVERMAP_ENGINE_LARGE_THRUST (OVERMAP_POD_THRUST * 12)
#define OVERMAP_POD_CRUISE 3

#define OVERMAP_POD_CELL_BURN_BASE 24
#define OVERMAP_POD_CELL_BURN_MAX 72
#define OVERMAP_POD_LANDING_TRIES 48
#define OVERMAP_SENSOR_LOG_MAX 80
#define OVERMAP_SENSOR_STEALTH_MASS_MED 3000
#define OVERMAP_SENSOR_STEALTH_MASS_HEAVY 7000
#define OVERMAP_SENSOR_STEALTH_SPEED_MED 4
#define OVERMAP_SENSOR_STEALTH_SPEED_SMALL 11
#define OVERMAP_SENSOR_KIND_LONG "long"
#define OVERMAP_SENSOR_KIND_SHORT "short"
#define OVERMAP_MASS_PER_TURF 1.2
#define OVERMAP_MASS_BASE 80
#define OVERMAP_MASS_STATION 2000

#define OVERMAP_MASS_INERTIA 10

#define OVERMAP_SENSOR_ALERT_SOUND 'sound/overmap/sensors/contactgeneric.ogg'
#define OVERMAP_SENSOR_DISTRESS_SOUND 'sound/machines/warning-buzzer.ogg'
#define OVERMAP_SENSOR_LOOP_SOUND 'sound/overmap/sensors/sensorloop.ogg'
#define OVERMAP_SENSOR_NEWCONTACT_SOUND 'sound/overmap/sensors/newcontact.ogg'
#define OVERMAP_SENSOR_LOST_SOUND 'sound/overmap/sensors/contact_lost.ogg'

#define OVERMAP_HAZARD_ICON_ASTEROID "hazard_asteroid"
#define OVERMAP_HAZARD_ICON_EMP "hazard_emp"
#define OVERMAP_HAZARD_ICON_CARP "hazard_carp"

#define OVERMAP_HAZARD_SAFE_SPEED 6

#define OVERMAP_HAZARD_SPEED_CAP 16
#define OVERMAP_HAZARD_HIT_CHANCE_CAP 75
#define OVERMAP_HAZARD_EMP_STRONG_CHANCE 10
#define OVERMAP_HAZARD_LIGHTNING_CHANCE 5
#define OVERMAP_HAZARD_IDLE_HIT_CHANCE 8
#define OVERMAP_HAZARD_CARP_COOLDOWN (30 SECONDS)
#define OVERMAP_HAZARD_CARP_MIN 2
#define OVERMAP_HAZARD_CARP_MAX 4
#define OVERMAP_HAZARD_CARP_CAP 12

#define OVERMAP_COMMS_COOLDOWN (60 SECONDS)
#define OVERMAP_COMMS_KEY_LEN 6
#define OVERMAP_COMMS_MAX_MESSAGES 40
#define OVERMAP_COMMS_MAX_BODY 4096
#define OVERMAP_COMMS_MAX_KEY 32

#define OVERMAP_RUIN_SIZE_SMALL "small"
#define OVERMAP_RUIN_SIZE_MEDIUM "medium"
#define OVERMAP_RUIN_SIZE_LARGE "large"

#define OVERMAP_RUIN_POOL_STATION "station"
#define OVERMAP_RUIN_POOL_WILD "wilderness"
