#define REFERRAL_BUDGET_SOURCE "referral"

#define REFERRAL_CODE_MAX_PLAYER_AGE_DAYS 7
#define REFERRAL_REQUIRED_MINUTES 600
#define REFERRAL_REQUIRED_DAYS 3
#define REFERRAL_REFERRER_MIN_MINUTES 1200
#define REFERRAL_LIMIT_PER_PERIOD 10
#define REFERRAL_LIMIT_PERIOD_DAYS 30
#define REFERRAL_REWARD_DAYS 7
#define REFERRAL_REWARD_MAX_DAYS 90
#define REFERRAL_INVITES_PER_TIER 3
