#define FIT_CACHE_DIRECTORY "data/adaptive_sprites"
#define FIT_CACHE_VERSION 7
#define FIT_CACHE_FLUSH_DELAY (30 SECONDS)
#define FIT_PART_GARMENT_SHARE 0.25
#define FIT_HEAD_WARP_SHARE 0.25
#define FIT_REFIT_MAX_GROWTH 8
#define FIT_REFIT_COMMON_COLOR 4
#define FIT_REFIT_RARE_COLOR 8
#define FIT_REFIT_COLOR_COST 4
#define FIT_REFIT_EDGE_COST 8
#define FIT_REFIT_RARE_COST 3
#define FIT_REFIT_DISTANCE_COST 0.6
