#define EXTRA_MONEY 10000

#define SSCAPITALISM_STAGE_IDLE 0
#define SSCAPITALISM_STAGE_BUILD_RUN 1
#define SSCAPITALISM_STAGE_PAY 2
#define SSCAPITALISM_STAGE_GOALS 3

SUBSYSTEM_DEF(capitalism)
	name = "Capitalism"
	dependencies = list(
		/datum/controller/subsystem/mapping,
	)
	runlevels = RUNLEVEL_GAME
	wait = 5 MINUTES
	ss_flags = SS_BACKGROUND | SS_KEEP_TIMING

	/// Account that receives money for orders, vending machines and station goal bounties.
	var/datum/money_account/base_account
	/// Account from which salaries are deducted.
	var/datum/money_account/payment_account

	// Statistics for the round-end report.
	/// Total credits paid out as salaries this round.
	var/total_salary_payment = 0
	/// Total credits routed to the station account from cargo bounty.
	var/total_station_bounty = 0
	/// Total credits routed to the cargo account from quest payouts.
	var/total_cargo_bounty = 0
	/// Total credits paid out as personal/department bounties this round.
	var/total_personal_bounty = 0
	/// Income generated by vending machines this round.
	var/income_vedromat = 0
	/// How many salary cycles ended in default. Useful greentext metric.
	var/default_counter = 0

	/// Station goals that have already paid out so we don't double-pay them.
	var/list/completed_goals = list()
	/// TRUE while the station can't make payroll. Other systems may key off this (e.g. cargo modifiers).
	var/default_status = FALSE

	/// Current stage of the resumable fire().
	var/fire_stage = SSCAPITALISM_STAGE_IDLE
	/// Snapshot of accounts queued for payout this fire. Drained as we process.
	var/list/currentrun = list()
	/// Sum of paychecks for everyone in `currentrun`, computed during the build stage.
	var/pending_salary_total = 0

/datum/controller/subsystem/capitalism/Initialize()
	accounts_init()
	salary_account_init()
	return SS_INIT_SUCCESS

/datum/controller/subsystem/capitalism/get_stat_details()
	return "Default:[default_status ? "Y" : "N"] | Stage:[fire_stage] | Run:[length(currentrun)]"

/datum/controller/subsystem/capitalism/fire(resumed = FALSE)
	if(!resumed)
		fire_stage = SSCAPITALISM_STAGE_BUILD_RUN

	if(fire_stage == SSCAPITALISM_STAGE_BUILD_RUN)
		build_payment_run()
		if(MC_TICK_CHECK)
			return
		fire_stage = SSCAPITALISM_STAGE_PAY

	if(fire_stage == SSCAPITALISM_STAGE_PAY)
		process_payments()
		if(state != SS_RUNNING)
			return
		fire_stage = SSCAPITALISM_STAGE_GOALS

	if(fire_stage == SSCAPITALISM_STAGE_GOALS)
		process_station_goals()

	fire_stage = SSCAPITALISM_STAGE_IDLE

/// Snapshots all accounts that should receive a salary this cycle and sums their paychecks.
/// Also resolves the default-status transition before any money is moved, so we don't half-pay.
/// If a previous fire() was interrupted mid-payout (charge failed), `currentrun` will still
/// hold the unpaid accounts — we resume that queue instead of rebuilding to avoid double-paying
/// anyone who already got their salary in the prior cycle.
/datum/controller/subsystem/capitalism/proc/build_payment_run()
	var/resuming = length(currentrun) > 0
	if(!resuming)
		for(var/datum/money_account/account as anything in GLOB.all_money_accounts)
			if(!account.salary_payment_active || !account.linked_job?.paycheck || account.suspended)
				continue
			currentrun += account

	pending_salary_total = 0
	for(var/datum/money_account/account as anything in currentrun)
		if(account.linked_job?.paycheck)
			pending_salary_total += account.linked_job.paycheck

	// Hysteresis: exiting default requires an EXTRA_MONEY buffer so we don't re-default next cycle.
	if(default_status && payment_account.money >= pending_salary_total + EXTRA_MONEY)
		default_status = FALSE
		default_announce()
		return

	if(default_status)
		// Still defaulted. Keep a resumed queue so we eventually pay it; drop a fresh one
		// since it would just be rebuilt next cycle anyway.
		if(!resuming)
			currentrun.Cut()
		default_counter++
		return

	if(payment_account.money >= pending_salary_total)
		return

	default_status = TRUE
	default_announce()
	if(!resuming)
		currentrun.Cut()
	default_counter++

/// Processes the payout queue across as many ticks as needed. Drains `currentrun`.
/datum/controller/subsystem/capitalism/proc/process_payments()
	var/list/cached_run = currentrun
	while(length(cached_run))
		var/datum/money_account/account = cached_run[length(cached_run)]
		cached_run.len--
		if(QDELETED(account) || !account.linked_job?.paycheck)
			continue
		var/paycheck = account.linked_job.paycheck
		if(!payment_account.charge(paycheck, account, "Выплата зарплаты персоналу.", "Отдел финансов \"Нанотрейзен\"", "Поступление зарплаты.", "Поступление зарплаты", "Терминал Бизель №[rand(111,333)]"))
			// payment_account ran dry mid-batch despite the pre-check (e.g. an admin debited it).
			// Flip to default and bail without clearing cached_run — build_payment_run() will
			// resume the remaining queue next cycle so no one gets paid twice or skipped.
			default_status = TRUE
			default_announce()
			default_counter++
			return
		account.notify_pda_owner("<b>Поступление зарплаты </b>\"На ваш привязанный аккаунт поступило [paycheck] кредитов\" (Невозможно Ответить)", FALSE)
		total_salary_payment += paycheck
		if(MC_TICK_CHECK)
			return

/// Walks the current gamemode's station goals, paying out any that completed since the last fire.
/datum/controller/subsystem/capitalism/proc/process_station_goals()
	if(!SSticker?.mode)
		return

	var/total_station_goal_bounty = 0
	var/list/extra_personal_bounty = list()
	for(var/datum/station_goal/goal in SSticker.mode.station_goals)
		if(!goal || (goal in completed_goals) || !goal.check_completion())
			continue
		completed_goals += goal
		total_station_goal_bounty += goal.station_bounty
		for(var/prom in goal.personal_reward)
			extra_personal_bounty[prom] = (extra_personal_bounty[prom] || 0) + goal.personal_reward[prom]
		if(MC_TICK_CHECK)
			break

	if(total_station_goal_bounty)
		base_account.credit(total_station_goal_bounty, "Начисление награды за выполнение цели.", "Отдел развития \"Нанотрейзен\"", base_account.owner_name)
		smart_job_payment(extra_personal_bounty)

/datum/controller/subsystem/capitalism/proc/default_announce()
	if(default_status)
		GLOB.minor_announcement.announce(
			message = "На счёте станции зафиксировано отсутствие финансовых средств. В связи с этим выплаты заработной платы были приостановлены. Руководству станции необходимо незамедлительно принять меры для разрешения сложившейся ситуации.",
			new_title = ANNOUNCE_CAPITAL_DEFOLT_RU,
			new_sound = SSstation.announcer.get_rand_report_sound()
		)
	else
		GLOB.minor_announcement.announce(
			message = "На счёте станции имеется достаточное количество средств для осуществления выплат. Заработная плата сотрудникам выплачивается в полном объёме.",
			new_title = ANNOUNCE_CAPITAL_REPAY_RU,
			new_sound = SSstation.announcer.get_rand_report_sound()
		)

/datum/controller/subsystem/capitalism/proc/accounts_init()
	if(!GLOB.CC_account)
		create_CC_account()

	if(!GLOB.station_account)
		create_station_account()

	if(!length(GLOB.department_accounts))
		for(var/department in GLOB.station_departments)
			create_department_account(department)

/datum/controller/subsystem/capitalism/proc/salary_account_init()
	base_account = GLOB.station_account
	payment_account = GLOB.station_account

	if(!GLOB.vendor_account)
		GLOB.vendor_account = base_account

/// Splits `money` evenly between every account whose linked job title is in `jobs_payment`.
/// Returns FALSE if no eligible accounts were found.
/datum/controller/subsystem/capitalism/proc/smart_bounty_payment(list/jobs_payment, money)
	if(!length(jobs_payment) || !money)
		return FALSE

	var/list/list_payment_accounts = list()
	total_personal_bounty += money
	for(var/datum/money_account/account as anything in GLOB.all_money_accounts)
		if(!jobs_payment.Find(account.linked_job?.title) || !account.salary_payment_active || account.suspended)
			continue
		list_payment_accounts[account] = TRUE

	if(!length(list_payment_accounts))
		return FALSE

	. = TRUE
	var/bounty = floor(money / length(list_payment_accounts))
	while(length(list_payment_accounts))
		var/datum/money_account/account = list_payment_accounts[length(list_payment_accounts)]
		list_payment_accounts.len--
		if(account.credit(bounty, "Начисление награды за выполнение заказа.", "Терминал Бизель №[rand(111,333)]", account.owner_name))
			account.notify_pda_owner("<b>Поступление награды </b>\"На ваш привязанный аккаунт поступило [bounty] кредитов за помощь в выполнении заказа.\" (Невозможно Ответить)", FALSE)

/// Pays a per-job bounty to every active account whose job is in `jobs_payment` (assoc list: title -> amount).
/datum/controller/subsystem/capitalism/proc/smart_job_payment(list/jobs_payment)
	if(!length(jobs_payment))
		return FALSE

	. = FALSE
	for(var/datum/money_account/account as anything in GLOB.all_money_accounts)
		var/job_title = account.linked_job?.title
		if(!jobs_payment[job_title] || !account.salary_payment_active || account.suspended)
			continue
		var/payout = jobs_payment[job_title]
		if(!account.credit(payout, "Начисление награды за выполнение цели.", "Терминал Бизель №[rand(111,333)]", account.owner_name))
			continue
		total_personal_bounty += payout
		account.notify_pda_owner("<b>Поступление награды </b>\"На ваш привязанный аккаунт поступило [payout] кредитов за помощь в выполнении цель станции.\" (Невозможно Ответить)", FALSE)
		. = TRUE

/// Splits `money` evenly between department accounts named in `keys_department`.
/// Falls back to crediting the station account if none of the departments resolve.
/datum/controller/subsystem/capitalism/proc/smart_department_payment(list/keys_department, money)
	if(!length(keys_department) || !money)
		return FALSE

	var/list/list_payment_accounts = list()
	total_personal_bounty += money

	for(var/key_account_department in keys_department)
		if(GLOB.department_accounts[key_account_department])
			list_payment_accounts[GLOB.department_accounts[key_account_department]] = TRUE

	if(!length(list_payment_accounts))
		// No department resolved — give the whole bounty to the station account as a fallback.
		base_account.credit(money, "Начисление награды за выполнение заказа.", "Терминал Бизель №[rand(111,333)]", base_account.owner_name)
		return TRUE

	var/bounty = floor(money / length(list_payment_accounts))
	while(length(list_payment_accounts))
		var/datum/money_account/account = list_payment_accounts[length(list_payment_accounts)]
		list_payment_accounts.len--
		account.credit(bounty, "Начисление награды за выполнение заказа.", "Терминал Бизель №[rand(111,333)]", account.owner_name)
	return TRUE

#undef EXTRA_MONEY
#undef SSCAPITALISM_STAGE_IDLE
#undef SSCAPITALISM_STAGE_BUILD_RUN
#undef SSCAPITALISM_STAGE_PAY
#undef SSCAPITALISM_STAGE_GOALS
