DEFINE_BITFIELD(appearance_flags, list(
	"LONG_GLIDE" = LONG_GLIDE,
	"RESET_COLOR" = RESET_COLOR,
	"RESET_ALPHA" = RESET_ALPHA,
	"RESET_TRANSFORM" = RESET_TRANSFORM,
	"NO_CLIENT_COLOR" = NO_CLIENT_COLOR,
	"KEEP_TOGETHER" = KEEP_TOGETHER,
	"KEEP_APART" = KEEP_APART,
	"PLANE_MASTER" = PLANE_MASTER,
	"TILE_BOUND" = TILE_BOUND,
	"PIXEL_SCALE" = PIXEL_SCALE,
	"PASS_MOUSE" = PASS_MOUSE,
	"TILE_MOVER" = TILE_MOVER,
))

DEFINE_BITFIELD(vis_flags, list(
	"VIS_HIDE" = VIS_HIDE,
	"VIS_INHERIT_DIR" = VIS_INHERIT_DIR,
	"VIS_INHERIT_ICON" = VIS_INHERIT_ICON,
	"VIS_INHERIT_ICON_STATE" = VIS_INHERIT_ICON_STATE,
	"VIS_INHERIT_ID" = VIS_INHERIT_ID,
	"VIS_INHERIT_LAYER" = VIS_INHERIT_LAYER,
	"VIS_INHERIT_PLANE" = VIS_INHERIT_PLANE,
	"VIS_UNDERLAY" = VIS_UNDERLAY,
))

DEFINE_BITFIELD(datum_flags, list(
	"DF_ISPROCESSING" = DF_ISPROCESSING,
	"DF_VAR_EDITED" = DF_VAR_EDITED,
	"DF_USE_TAG" = DF_USE_TAG,
))

DEFINE_BITFIELD(pass_flags, list(
	"PASSTABLE" = PASSTABLE,
	"PASSGLASS" = PASSGLASS,
	"PASSGRILLE" = PASSGRILLE,
	"PASSBLOB" = PASSBLOB,
	"PASSMOB" = PASSMOB,
	"LETPASSTHROW" = LETPASSTHROW,
	"PASSMACHINE" = PASSMACHINE,
	"PASSSTRUCTURE" = PASSSTRUCTURE,
	"PASSFLAPS" = PASSFLAPS,
	"PASSFENCE" = PASSFENCE,
	"PASSDOOR" = PASSDOOR,
	"PASSVEHICLE" = PASSVEHICLE,
	"PASSITEM" = PASSITEM,
	"LETPASSCLICKS" = LETPASSCLICKS,
))

DEFINE_BITFIELD(pass_flags_self, list(
	"PASSTABLE" = PASSTABLE,
	"PASSGLASS" = PASSGLASS,
	"PASSGRILLE" = PASSGRILLE,
	"PASSBLOB" = PASSBLOB,
	"PASSMOB" = PASSMOB,
	"LETPASSTHROW" = LETPASSTHROW,
	"PASSMACHINE" = PASSMACHINE,
	"PASSSTRUCTURE" = PASSSTRUCTURE,
	"PASSFLAPS" = PASSFLAPS,
	"PASSFENCE" = PASSFENCE,
	"PASSDOOR" = PASSDOOR,
	"PASSVEHICLE" = PASSVEHICLE,
	"PASSITEM" = PASSITEM,
	"LETPASSCLICKS" = LETPASSCLICKS,
))


DEFINE_BITFIELD(gas_type, list(
	"LINDA_SPAWN_HEAT" = LINDA_SPAWN_HEAT,
	"LINDA_SPAWN_20C" = LINDA_SPAWN_20C,
	"LINDA_SPAWN_TOXINS" = LINDA_SPAWN_TOXINS,
	"LINDA_SPAWN_OXYGEN" = LINDA_SPAWN_OXYGEN,
	"LINDA_SPAWN_CO2" = LINDA_SPAWN_CO2,
	"LINDA_SPAWN_NITROGEN" = LINDA_SPAWN_NITROGEN,
	"LINDA_SPAWN_N2O" = LINDA_SPAWN_N2O,
	"LINDA_SPAWN_AGENT_B" = LINDA_SPAWN_AGENT_B,
	"LINDA_SPAWN_AIR" = LINDA_SPAWN_AIR,
))

DEFINE_BITFIELD(spawn_contents, list(
	"LINDA_SPAWN_HEAT" = LINDA_SPAWN_HEAT,
	"LINDA_SPAWN_20C" = LINDA_SPAWN_20C,
	"LINDA_SPAWN_TOXINS" = LINDA_SPAWN_TOXINS,
	"LINDA_SPAWN_OXYGEN" = LINDA_SPAWN_OXYGEN,
	"LINDA_SPAWN_CO2" = LINDA_SPAWN_CO2,
	"LINDA_SPAWN_NITROGEN" = LINDA_SPAWN_NITROGEN,
	"LINDA_SPAWN_N2O" = LINDA_SPAWN_N2O,
	"LINDA_SPAWN_AGENT_B" = LINDA_SPAWN_AGENT_B,
	"LINDA_SPAWN_AIR" = LINDA_SPAWN_AIR,
))

DEFINE_BITFIELD(qdel_flags, list(
	"QDEL_ITEM_ADMINS_WARNED" = QDEL_ITEM_ADMINS_WARNED,
	"QDEL_ITEM_SUSPENDED_FOR_LAG" = QDEL_ITEM_SUSPENDED_FOR_LAG,
))

DEFINE_BITFIELD(movement_type, list(
	"GROUND" = GROUND,
	"FLYING" = FLYING,
	"VENTCRAWLING" = VENTCRAWLING,
	"FLOATING" = FLOATING,
	"PHASING" = PHASING,
	"UPSIDE_DOWN" = UPSIDE_DOWN,
))

DEFINE_BITFIELD(area_flags, list(
	"UNIQUE_AREA" = UNIQUE_AREA,
	"BLOBS_ALLOWED" = BLOBS_ALLOWED,
	"CAVES_ALLOWED" = CAVES_ALLOWED,
	"FLORA_ALLOWED" = FLORA_ALLOWED,
	"MEGAFAUNA_SPAWN_ALLOWED" = MEGAFAUNA_SPAWN_ALLOWED,
	"MOB_SPAWN_ALLOWED" = MOB_SPAWN_ALLOWED,
))

DEFINE_BITFIELD(turf_flags, list(
	"NOJAUNT" = NOJAUNT,
	"UNUSED_RESERVATION_TURF" = UNUSED_RESERVATION_TURF,
	"RESERVATION_TURF" = RESERVATION_TURF,
	"NO_LAVA_GEN" = NO_LAVA_GEN,
	"NO_RUINS" = NO_RUINS,
))
