DEFINE_BITFIELD(department_flag, list(
	"JOBCAT_ENGSEC" = JOBCAT_ENGSEC,
	"JOBCAT_MEDSCI" = JOBCAT_MEDSCI,
	"JOBCAT_SUPPORT" = JOBCAT_SUPPORT,
	"JOBCAT_KARMA" = JOBCAT_KARMA,
))

DEFINE_BITFIELD(departments_bitflags, list(
	"SECURITY" = DEPARTMENT_BITFLAG_SECURITY,
	"COMMAND" = DEPARTMENT_BITFLAG_COMMAND,
	"SERVICE" = DEPARTMENT_BITFLAG_SERVICE,
	"SUPPLY" = DEPARTMENT_BITFLAG_SUPPLY,
	"ENGINEERING" = DEPARTMENT_BITFLAG_ENGINEERING,
	"SCIENCE" = DEPARTMENT_BITFLAG_SCIENCE,
	"MEDICAL" = DEPARTMENT_BITFLAG_MEDICAL,
	"LEGAL" = DEPARTMENT_BITFLAG_LEGAL,
))
