/mob/living/silicon/Login()
	SetSleeping(0)
	if(player_logged)
		overlays -= image('icons/effects/effects.dmi', icon_state = "zzz_glow_silicon")
	if(mind && SSticker && SSticker.mode)
		SSticker.mode.remove_revolutionary(mind, 1)
		SSticker.mode.remove_cultist(mind, 1)
		SSticker.mode.remove_wizard(mind)
		mind.remove_antag_datum(/datum/antagonist/ninja)
		mind.remove_antag_datum(/datum/antagonist/changeling)
		mind.remove_antag_datum(/datum/antagonist/vampire)
		mind.remove_antag_datum(/datum/antagonist/goon_vampire)
		mind.remove_antag_datum(/datum/antagonist/thief)
		SSticker.mode.remove_thrall(mind, 0)
		SSticker.mode.remove_shadowling(mind)
		SSticker.mode.remove_abductor(mind)
	..()

/mob/living/silicon/Logout()
	. = ..()
	if(isLivingSSD(src))
		overlays += image('icons/effects/effects.dmi', icon_state = "zzz_glow_silicon")
