# Okay, this is a Gemini config, but the default values ​​are fine for us.
# Here's the link if anyone ever wants to change anything: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github?hl=ru
