name: "Discord PR Notification"
on:
  pull_request_target:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-24.04
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        uses: littleboobs/discord-notify@v1.0-ss1984
        if: ${{ steps.secrets_set.outputs.SECRETS_ENABLED }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ github.event.pull_request.user.login }} - ${{ github.event.pull_request.title }}
          message: GET_ACTION
          include_image: false
          show_author: true
          avatar_url: https://cdn.discordapp.com/attachments/1284433984666734603/1403077083076366546/1984.png?ex=68963cdc&is=6894eb5c&hm=7f654bcb85dec940417a6e393b461382e7284d545f8336807bc753a38b040e01&
          username: Почтальон
          title_url: "${{ github.event.pull_request.html_url }}"
