name: Generate web assets

on:
  schedule:
    - cron: "0 0 * * *" # Every day at the very start of the day. Except it happens an hour and a half later because actions backlog
  workflow_dispatch:

jobs:
  generate_static_assets:
    name: "Generate web assets"
    runs-on: ubuntu-24.04
    concurrency: gen-assets
    steps:
      - name: "Update Branch"
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: master220
      - name: "Install DMDOC"
        run: bash tools/ci/install_dmdoc.sh
      - name: "Generate documentation and static assets"
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
          mv tgui/public/ dmdoc/assets
        # Nojekyll is important to disable jeykll syntax, which can mess with files that start with underscores

      - name: "Deploy Documentation"
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: dmdoc
          keep_history: false
          build_dir: dmdoc
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
