name: Run Station Mapload Tests

on:
  workflow_call:
    inputs:
      stations:
        required: true
        type: string

jobs:
  run:
    uses: ./.github/workflows/run_station_test.yml
    strategy:
      fail-fast: false
      matrix:
        station: ${{ fromJSON(inputs.stations) }}
    with:
      station: ${{ matrix.station }}
