name: Run Station Test

on:
  workflow_call:
    inputs:
      station:
        required: true
        type: string

jobs:
  run_station_test:
    name: Station Test (${{ inputs.station }}; ${{ matrix.byondtype }})
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        byondtype: ["STABLE"]
    steps:
      - uses: actions/checkout@v6

      - name: Restore BYOND from Cache
        uses: ./.github/actions/restore_or_install_byond
        with:
          release: ${{ matrix.byondtype }}

      - name: Download build outputs
        uses: actions/download-artifact@v8
        with:
          name: build-artifact-station
          path: ./

      - name: Install RUST_G
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libgcc-s1:i386
          sudo apt install libcurl4:i386
          bash tools/ci/install_rustg.sh

      - name: Run Station Test
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          mkdir -p data
          echo '/datum/map/${{ inputs.station }}' > data/next_map.txt
          tools/ci/run_server.sh
