name: Run Station Test

on:
  workflow_call:
    inputs:
      station:
        required: true
        type: string

jobs:
  run_station_test:
    name: Station Test (${{ inputs.station }}; ${{ matrix.byondtype }})
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    container: ghcr.io/ss220-space/ubuntu-24.04:latest
    strategy:
      fail-fast: false
      matrix:
        byondtype: ["STABLE"]
    steps:
      - uses: actions/checkout@v7

      - name: Download build outputs
        uses: actions/download-artifact@v8
        with:
          name: build-artifact-station
          path: ./

      - name: Install RUST_G
        run: |
          bash tools/ci/install_rustg.sh

      - name: Run Station Test
        run: |
          mkdir -p data
          echo '/datum/map/${{ inputs.station }}' > data/next_map.txt
          tools/ci/run_server.sh
