on:
  workflow_call:

jobs:
  setup_build_artifact_station_tests:
    name: Setup build artifact # MAP_TESTS
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        byondtype: ['STABLE']
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: ./tgui/yarn.lock

      - name: Restore BYOND from Cache
        uses: ./.github/actions/restore_or_install_byond
        with:
          release: ${{ matrix.byondtype }}

      - name: Compile with MAP_TESTS
        run: |
          tools/ci/install_byond.sh '${{ matrix.byondtype }}'
          source $HOME/BYOND/byond/bin/byondsetup
          tools/ci/dm.sh -DMAP_TESTS -DMULTIINSTANCE -DCIBUILDING paradise.dme

      - name: Setup variable for output path
        run: |
          OUTPUT_DIR="target-station"
          echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV

      - name: Copy output files
        run: bash tools/ci/copy_build_output.sh $OUTPUT_DIR

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact-station
          path: ${{ env.OUTPUT_DIR }}
          retention-days: 1
